### ISSUE TITLE
Relationships example causing RecursionErrors

### ISSUE THREAD

**Issue by austinv11** [tanghaibao/goatools#101]
I was following along with this example notebook: https://github.com/tanghaibao/goatools/blob/master/notebooks/relatonships_in_the_go.ipynb and running the following snippet:
```python
from goatools.obo_parser import GODag
import wget

go_fn = wget.download('http://geneontology.org/ontology/go.obo')
go = GODag(go_fn, optional_attrs=['relationship'])
```
Is causing a 
```
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Is the example notebook bugged?

**Comment by dvklopfenstein** [comment]
I believe that this is now properly updated and working and so will close this issue. Please be free to open a new issue if you find this is not the case.

Thank you again for your interest in GOATOOLS and taking the time to alert us of this issue.
