### ISSUE TITLE
Different enrichment results between after issue #96 fix

### ISSUE THREAD

**Issue by hag007** [tanghaibao/goatools#106]
Hi

Thank you for this library. It is very helpful for my project.

In one of my enrichment tests I encountered an issue, similar to that of issue #96 
I saw the solution on that and I took the that fix (I tried it two times: manually and by installing dev version).
However, running the code after the fix over yielded different results to the ones I got before (on enrichment tests that worked properly).

Attached the code (isolated it as possible):
[go_issue_2.zip](https://github.com/tanghaibao/goatools/files/2149672/go_issue_2.zip)

The relevant code is under "go_issue.py", function "check_group_enrichment"
To run it just execute "python go_issue.py"
Results will appear as an Excel file insode the same folder.

To reproduce the issue install run on Windows 10, python 2.7.  Execute the code after installing stable version (easy_install goatools), then remove goatools and reinstall dev version (pip install git+git://github.com/tanghaibao/goatools.git) and compare the Excels

Thanks in advance.

**Comment by dvklopfenstein** [comment]
Thank you for your interest in GOATOOLS and for taking the time to write us.

Thank you for adding an example that we may work with. I have downloaded and unzipped your code. Upon running the code, there is a message about an missing module named _constants_. Can you provide a link to the _constants_ module?:    

```
python go_issue.py    
Traceback (most recent call last):    
  File "go_issue.py", line 5, in <module>    
    from download_resources_issue import download    
  File "/cygdrive/c/Users/note2/Data/git/goatools/i106/download_resources_issue.py", line 2, in <module>    
    import constants    
ImportError: No module named constants    
```

**Comment by dvklopfenstein** [comment]
Never mind about the "constants" issue. I commented "import constants" out of _download_resources_issue.py_ and got further in the run.

**Comment by dvklopfenstein** [comment]
It looks like I am missing _'./dictionaries\\/ensembl2entrez.txt'_    
    
Here is the error message:    
```
python go_issue.py
./GO\/go-basic.obo: fmt(1.2) rel(2018-06-28) 47,231 GO Terms
  20,323 items READ: ./GO\/gene2go
Traceback (most recent call last):
  File "go_issue.py", line 109, in <module>
    check_group_enrichment("warburg_high.txt","rfe_uvm_1000_3124.txt")
  File "go_issue.py", line 47, in check_group_enrichment
    g = GOEnrichmentStudy([int(cur) for cur in ensembl2entrez_convertor(total_gene_list)],
  File "/cygdrive/c/Users/note2/Data/git/goatools_alpha/issues/i106/ensembl2entrez_issue.py", line 69, in ensembl2entrez_convertor
    ensembl2entrez_dict = get_ensembl2entrez_dictionary()
  File "/cygdrive/c/Users/note2/Data/git/goatools_alpha/issues/i106/ensembl2entrez_issue.py", line 53, in get_ensembl2entrez_dictionary
    lines_dict = load_gene_dictionary(constants_issue.ENSEMBL_TO_ENTREZ)
  File "/cygdrive/c/Users/note2/Data/git/goatools_alpha/issues/i106/ensembl2entrez_issue.py", line 31, in load_gene_dictionary
    f = open(gene_list_path,'r')
IOError: [Errno 2] No such file or directory: './dictionaries\\/ensembl2entrez.txt'
```

**Comment by hag007** [comment]
Hi
Sorry about that. could you try with the attached version?
[go_issue_3.zip](https://github.com/tanghaibao/goatools/files/2150071/go_issue_3.zip)
(constant issue corrected as well)

**Comment by hag007** [comment]
P.S after playing a bit with the source code my guess is that the newer results (e.g dev version) gets the correct results, but I'm not sure..

**Comment by dvklopfenstein** [comment]
Thank you! I successfully downloaded go_issue_3.zip and will investigate.

I will do a comparison with and with out the i96 fix using the same GO-DAG and annotations so that we can see the effect of the fix.
