### ISSUE TITLE
plot_go.py on Conda version of GOATools

### ISSUE THREAD

**Issue by asulit08** [tanghaibao/goatools#108]
Hi,

I am looking for a way to plot multiple GOs into one graph and I saw this thread https://github.com/tanghaibao/goatools/issues/102

However, I can't seem to locate the plot_go.py functionality in my version of GOATools which I have installed through Conda. Is there a way I can use this?

Thank you

**Comment by dvklopfenstein** [comment]
Thank you for your interest in GOATOOLS and for taking the time to write to us.

Our last release to PyPI was GOATOOLS version 0.8.4 on Apr 28, 2018. The go_plot.py script was added Jun 15, 2018. @tanghaibao, can release the latest GOATOOLS to PyPI?

If you do not want to wait for an update in PyPI, you can access the latest GOATOOLS (and the newly available **scripts/go_plot.py**) by cloning the repository and then running the goatools/scripts/go_plot.py script from there. You will also need to add your clone of goatools to your PYTHONPATH like this:

export PYTHONPATH=.:/<goatools_repo>/

where if you did 'cd <goatools_repo>', and did 'ls', you would see:
```
$ ls
data  goatools  makefile     notebooks  requirements.txt  scripts   setup_helper.py  tests
doc   LICENSE   MANIFEST.in  README.md  run.sh            setup.py  sphinx
```

**Comment by tanghaibao** [comment]
@dvklopfenstein 
I'll make a release once travis CI tests pass. Would you look into the failed cases for the latest commit?

**Comment by dvklopfenstein** [comment]
The tests now pass.

The latest go-basic.obo has an illegal line in one of the synonyms which resulted in our obo parser exiting early. This is new.

I submitted an issue to the gene ontology organization regarding the obo line and changed our code to allow reading of that line, but report a warning while reading., which is documented in https://github.com/tanghaibao/goatools/issues/109

**Comment by tanghaibao** [comment]
@dvklopfenstein PyPI now updated - let me know if there's an issue
