### ISSUE TITLE
Custom association files

### ISSUE THREAD

**Issue by rafarios50** [tanghaibao/goatools#110]
I would like to use my own association file, as the organism im working is not a model one.

I have got associations between my annotated genes and GO:terms by using interproscan.

I have found the documentation for the GAF format (http://geneontology.org/page/go-annotation-file-format-20), but wasnt sure if im going to need to use all those columns for my custom annotation, or there are some that are not needed in goatools.

What do you recommend me to do to create a functional go enrichment analysis based on my annotation and its association to GO:terms?

I have seen the example file in the test folder, and it only have two columns, and the second has long lists of GO:terms. In my annotation some of the genes have many GO:terms associated, Should those be from the same ontology or can those be mixed in the association file? Resulting in one association file per ontology, or can those be mixed?

Thanks.

**Comment by dvklopfenstein** [comment]
Thank you for your interest in GOATOOLS and for taking the time to write.

Can you send the file (or a subset) containing your annotated genes and GO terms created using interproscan?

Are you using the script, scripts/find_enrichment.py?

**Comment by rafarios50** [comment]
Thank you for your response.

At the moment I havent try running goatools, as I wanted to ask first how should I do it.

I ran the scripts/find_enrichment.py with the test data (study, population and association), and it worked. I was thinking to prepare similar files with my data to do the analysis.

This is a subset of my annotations in the format as I saw it in the association file:

> 225_group_12047_12      GO:0003924;GO:0005525
165_group_10247_9       GO:0006508;GO:0008233
55_group_8947_9 GO:0003676;GO:0003723;GO:0005524
193_group_11378_4       GO:0003676
228_group_13568_2       GO:0003735;GO:0005840;GO:0003723;GO:0006412;GO:0005622
105_group_9815_16       GO:0043190;GO:0016021;GO:0016020;GO:0071705;GO:0022857;GO:0055085
234_group_8207_4        GO:0008444;GO:0016020;GO:0016021;GO:0016780;GO:0008654
229_group_13685_4       GO:0008113;GO:0055114
239_group_10964_3       GO:0006228;GO:0006241;GO:0004550;GO:0006183;GO:0006165
212_group_10983_14      GO:0022857;GO:0016020;GO:0055085
145_group_6134_4        GO:0005515

Here in the preview the tabs are lost, but there are two columns, one with the name of the gene and the second the goterms, not sure if this format would work.

Thanks again.

**Comment by rafarios50** [comment]
Also, I saw this notebook: https://github.com/tanghaibao/goatools/blob/master/notebooks/goea_nbt3102.ipynb

And would like to do the plot with all the significant GOterms, but im not sure how to load my custom association file to create the GOEA object.

Also, couldnt find the example files to run the notebook.

Could you please help me explaining me how to do that, or where to find the example files?

Thanks,

**Comment by dvklopfenstein** [comment]
Your association file containing the DNA items named like 225_group_12047_12 and 165_group_10247_9 should work just fine. I successfully tried loading the subset example that you provided. 

Please try the GOEA using your custom file. If there are any issues, please let us know.

**Comment by dvklopfenstein** [comment]
Please open a new issue for your comment about plotting so we can keep one issue per issue report. I promise that we will get you running on the plots.

**Comment by rafarios50** [comment]
The GOEA worked fine with the custom file.

Will create a new issue for the plot.

Thanks!
