### ISSUE TITLE
AttributeError: I'm having a hard time solving this issue.

### ISSUE THREAD

**Issue by cross12tamu** [tanghaibao/goatools#111]
Hopefully I'm not going to bother you guys with a really mundane, simple, "totally my fault error"; but, at the same time, perhaps those are the best type of issues! :)

So, I first ran my code in the google collab notebook to do an enrichment study . Long story short, it worked, but I had a hard time getting the print_summary function to work, but got the print_results function to work instead, and went with that. Turns out, I like the additional statistics it provides, so I wish to continue using that function.

I then run the script through terminal, and I get the following error:

`AttributeError: 'GOEnrichmentStudy' object has no attribute 'print_results'`

I'm curious as to what I am doing wrong? A cut out of my code is below, let me know if you need anymore information/code/files. Of note, when running from terminal, I got the print_summary function to perform (I'm going crazy). Again I hope this is a simple issue to resolve!

Thanks in advance,

Curtis

```ecoli_keys = GAF_ecoli.keys()
study = tca_dict.keys()
methods = ['fdr']

g = GOEnrichmentStudy(ecoli_keys, matches_reference, obodag,
                      propagate_counts = True, alpha = 0.05,
                      methods = methods)

g_res = g.run_study(study)

print('\n\n#----------------------------------------------------------------------#')
print('#----------------------------------------------------------------------#')
print('#--------------------------------#')
print('#----------------------------------------------------------------------#')
print('#----------------------------------------------------------------------#\n\n')

g.print_results(g_res) #these ticks are not on actual code```

**Comment by dvklopfenstein** [comment]
Hello Curtis,

Thank you for your interest in GOATOOLS and taking the time to write us.  

Did you get the GOATOOLS package from github (eg, "git clone …GOATOOLS..." or from PyPI (eg, "pip install GOATOOLS")? Can include the full error messages?


What version of the GOATOOLS are you using? 
```
import goatools
print(goatools.__version__)
```

**Comment by cross12tamu** [comment]
I did the easy_install I believe (honestly, don't quite remember).

I'm running the 0.8.4 version:


And here's the full error result from terminal:

``` Traceback (most recent call last):
  File "GOATOOLS_survival.py", line 83, in <module>
    g.print_results(g_res)
AttributeError: 'GOEnrichmentStudy' object has no attribute 'print_results'
```

And from Spyder:
``` 
Traceback (most recent call last):

  File "<ipython-input-7-0d638d4d78c9>", line 1, in <module>
    runfile('/home/cross12tamu/.config/spyder-py3/GOATOOLS_survival.py', wdir='/home/cross12tamu/.config/spyder-py3')

  File "/home/cross12tamu/Research/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 678, in runfile
    execfile(filename, namespace)

  File "/home/cross12tamu/Research/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 106, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/cross12tamu/.config/spyder-py3/GOATOOLS_survival.py", line 83, in <module>
    g.print_results(g_res)

AttributeError: 'GOEnrichmentStudy' object has no attribute 'print_results' 
```


Thank you so much for the prompt reply.

Curtis

**Comment by dvklopfenstein** [comment]
The latest GOATOOLS version is 0.8.9.

Try updating your GOATOOLS and then re-running.
```
pip install --upgrade goatools
```

Also, if you comment out the line, "g.print_results(g_res)", does your script work?

**Comment by dvklopfenstein** [comment]
Can you include a copy of your import statements?

**Comment by cross12tamu** [comment]
The upgrade actually fixed the function for me. Now the print_results works.

And, when I ran this before, the script would run and just get that error when it hit g.print_results at the end of the script.

SO, for now, the print_results is solved, however, now the print_summary is giving me...odd results? I'll link results in just a sec (as well as do the other commands from your most recent post).

**Comment by cross12tamu** [comment]
**1st, the dir prints**
```
print(dir(GOEnrichmentStudy))
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_log_multitest_corr', '_run_multitest_corr', '_run_multitest_local', '_run_multitest_statsmodels', '_update_pvalcorr', 'get_adj_records', 'get_item_cnt', 'get_ns2nts', 'get_prtflds_default', 'get_pval_uncorr', 'get_results_msg', 'print_results', 'print_results_adj', 'print_summary', 'prt_tsv', 'prt_txt', 'run_study', 'run_study_nts', 'wr_py_goea_results', 'wr_tsv', 'wr_txt', 'wr_xlsx']

print(dir(g))
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_log_multitest_corr', '_run_multitest', '_run_multitest_corr', '_run_multitest_local', '_run_multitest_statsmodels', '_update_pvalcorr', 'alpha', 'assoc', 'get_adj_records', 'get_item_cnt', 'get_ns2nts', 'get_prtflds_default', 'get_pval_uncorr', 'get_results_msg', 'go2popitems', 'log', 'methods', 'obo_dag', 'pop', 'pop_n', 'print_results', 'print_results_adj', 'print_summary', 'prt_tsv', 'prt_txt', 'pval_obj', 'run_study', 'run_study_nts', 'wr_py_goea_results', 'wr_tsv', 'wr_txt', 'wr_xlsx']
```

**2nd, print_results v. print_summary**

Here is the first "result" from g.print_results:

```
GO      NS      enrichment      name    ratio_in_study  ratio_in_pop    p_uncorrected   depth   study_count     p_fdr   study_items
GO:0006101      BP      e       citrate metabolic process       9/16    10/3623 5.25e-08        n.a.    9       0       P05042, P0A836, P0AC33, P0AC41, P0AFG3, P14407, P25516, P36683, P61889
```

Here is are the results from g.print_summary:
```
# Generated by GOATOOLS v0.8.9 (2018-10-04)
# min_ratio=[GOEnrichmentRecord(GO:0006101), GOEnrichmentRecord(GO:0006099), GOEnrichmentRecord(GO:0072350), GOEnrichmentRecord(GO:0006091), GOEnrichmentRecord(GO:0017144), GOEnrichmentRecord(GO:0045333), GOEnrichmentRecord(GO:0015980), GOEnrichmentRecord(GO:0016999), GOEnrichmentRecord(GO:0009060), GOEnrichmentRecord(GO:0019752), GOEnrichmentRecord(GO:0043436), GOEnrichmentRecord(GO:0006082), GOEnrichmentRecord(GO:0055114), GOEnrichmentRecord(GO:0044237), GOEnrichmentRecord(GO:0008152), GOEnrichmentRecord(GO:0006097), GOEnrichmentRecord(GO:0006108), GOEnrichmentRecord(GO:0044281), GOEnrichmentRecord(GO:0017004), GOEnrichmentRecord(GO:0046487), GOEnrichmentRecord(GO:0009061), GOEnrichmentRecord(GO:0009987), GOEnrichmentRecord(GO:0006106), GOEnrichmentRecord(GO:0022900),
```
...and this continues for many more GO terms.

So, I had g.summary working yesterday, with g.print_results NOT working. Today (after update), g.summary works but not in the same way, with g.print_results working. 

¯\_(ツ)_/¯

**Comment by dvklopfenstein** [comment]
I am so glad that print_results is working for you. I am going to close this issue.

**Please open a new issue for the _summary_ issues**. We can track things better if we do this.

Thank you again for your interest in GOATOOLS. I will take a look at the summary that you are seeing.

**Comment by cross12tamu** [comment]
I will do so later this afternoon, and certainly by tomorrow morning!

Thank you again for the prompt replies and assistance.

Curtis
