### ISSUE TITLE
GO depth not reported if --outfile is not specified

### ISSUE THREAD

**Issue by jamiemcg** [tanghaibao/goatools#114]
Hello,

I've noticed that `find_enrichment.py` only reports the depth of GO terms if the user specifies an outfile (`--outfile`).

If you run `find_enrichment.py` without specifiying an output file, i.e. just printing the results to the terminal or redirecting to a file, GO term depths are reported as "n.a."

If you specify an output file (either tsv or xlsx), the GO term depth is reported as expected.

I'm not sure if this is the desired behaviour so I thought I would report it.

Thanks,
Jamie

**Comment by dvklopfenstein** [comment]
Thank you for taking the time to write to us and for your interest in GOATOOLS.

I have updated the code so that the depth is now displayed when running a gene ontology enrichment analysis and printing the results to the screen.
