### ISSUE TITLE
propagate counts considering part_of and other relationships 

### ISSUE THREAD

**Issue by dgpinheiro** [tanghaibao/goatools#117]
The same way as already mentioned by other colleagues, we are also interested in an implementation considering relationships, such as part_of, to propagate counts on them.

**Comment by dvklopfenstein** [comment]
I will take a look at this this week.

Thank you for taking your time to contact us regarding propagate counts using relationships.

**Comment by dvklopfenstein** [comment]
FYI: I just completed adding functionality for #126, which is a prerequisite for addressing your issue.

Withe #126 functinality implemented, I will now work on this issue.

Thank you very much for your interest in GOATOOLS, taking the time to write us, and for your patience. I look forward to implementing this issue.

**Comment by dvklopfenstein** [comment]
GOATOOLS now supports traversing optional relationships, like *part_of* and *regulates*, when propagating counts using these two new arguments in *scripts/find_enrichment.py*:
```
  -r, --relationship    Propagate counts up all relationships (default: False)
  --relationships [RELATIONSHIPS [RELATIONSHIPS ...]]
                        Propagate counts up user-specified relationships
                        (default: None)
```
You can specify all relationships using the ***-r*** argument. Or you can select specific relationships to use in propagate counts using the ***--relationships*** argument:

```
        # NO --relationships arg            -> None
        # --relationships part_of regulates -> relationships=['part_of', 'regulates']
        # --relationships=part_of           -> relationships=['part_of']
        # --relationships=part_of,regulates -> relationships=['part_of', 'regulates']
        # --relationships=part_of regulates -> NOT VALID
```

If you are running GOEAs from your own scripts, then you would access this new functionality using the ***relationships*** keyword argument in an instance of ***GOEnrichmentStudy***:

```
    goeaobj = GOEnrichmentStudy(
        geneids_population,
        assoc_geneid2gos,
        godag,
        propagate_counts=propagate_counts,
        relationships=VALUE,
        alpha=0.05,
        methods=['fdr_bh'])
    results = goeaobj.run_study(geneids_study, prt=prt)
```

Where **VALUE** is a set of relationships or a bool:
```
relationships=False
relationships=True  # All relationships are used in propagate counts
relationships={'regulates', 'negatively_regulates', 'positively_regulates'}
relationships={'part_of'}
```

**Comment by dvklopfenstein** [comment]
@tanghaibao , Can you release a new version of GOATOOLS? All the tests are passing and this new version will include a substantial increase in functionality in using the optional GODAG relationships.

**Comment by tanghaibao** [comment]
@dvklopfenstein 
Just upgraded to [v0.9.7](https://github.com/tanghaibao/goatools/commit/9adb8d9cfd8a6134a784002e434b6816086c3561). let me know if there's an issue.

**Comment by Melnorme1984** [comment]
Maybe the `update_association` method here should be updated to use this new functionality: https://github.com/tanghaibao/goatools/blob/master/goatools/obo_parser.py

**Comment by dvklopfenstein** [comment]
@Melnorme1984 FYI: the update_association function in GODag is deprecated and not used in GOEAs. It will be removed in a later release.
