### ISSUE TITLE
quickgo doesnt provide xml files

### ISSUE THREAD

**Issue by jeffsmith8** [tanghaibao/goatools#118]
Hi, I'm trying to follow your jupyter notebooks tutorial, however, exercise 2.3 I run into an issue whereby quickgo returns only an html file, not an oboxml.

`from future.standard_library import install_aliases
install_aliases()
from urllib.request import urlopen
import xmltodict

oboxml = urlopen('http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0003723&format=oboxml')
obo_dict = oboxml.read()
obo_dict_parse = `xmltodict.parse(obo_dict)`

which returns the error:

ExpatError Traceback (most recent call last) in 6 oboxml = urlopen('http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0003723&format=oboxml') 7 obo_dict = oboxml.read() ----> 8 obo_dict_parse = xmltodict.parse(obo_dict)

~/anaconda3/lib/python3.6/site-packages/xmltodict.py in parse(xml_input, encoding, expat, process_namespaces, namespace_separator, disable_entities, **kwargs) 328 parser.ParseFile(xml_input) 329 else: --> 330 parser.Parse(xml_input, True) 331 return handler.item 332

ExpatError: syntax error: line 1, column 0`

How are you getting around this? if at all?
The API documentation in quickgo and bioservices seems to be unhelpful.

**Comment by dvklopfenstein** [comment]
Thank you for your interest in GOATOOLS and for taking the time to contact us.

The search in QuickGO (not using GOATOOLS) seems to not be working:
![image](https://user-images.githubusercontent.com/7278188/51808073-38195d00-225d-11e9-8894-184217d53246.png)

GO:0003723 ('RNA binding' in the _molecular function_ branch) exists in the most recent GO-DAG, but does not seem to be seen from the QuickGO web-site.  I have tried searching for other terms on Quick GO, always returning 'No results'.

I have contacted QucikGO through their web site to ask about this...

**Comment by jeffsmith8** [comment]
Hi David, thanks for your response.
The whole quickgo site seems to be experiencing issues because currently it yield nothing for any search. When the site starts up again, however, the problem will still be present- format=oboxml still will not work. It would seem that xml formats are not even an option: 

https://www.ebi.ac.uk/QuickGO/api/index.html#!/annotations/downloadLookupUsingGET

even the bioservices tools do not work, I posted about this on stackoverflow earlier
https://stackoverflow.com/questions/54357717/xmltodict-expaterror-syntax-error-line-1-column-0-getting-xml-from-quickgo

**Comment by dvklopfenstein** [comment]
Thank you for the information and link.

Which Jupyter notebooks tutorial are you trying? I am not seeing any text, 'xml', in the our Jupyter notebooks:

```
$ find . -name \*.ipynb | xargs grep xml

$ find . -name \*.ipynb
./notebooks/.ipynb_checkpoints/annotation_coverage-checkpoint.ipynb
./notebooks/.ipynb_checkpoints/cell_cycle-checkpoint.ipynb
./notebooks/.ipynb_checkpoints/goea_nbt3102-checkpoint.ipynb
./notebooks/.ipynb_checkpoints/goea_nbt3102_all_study_genes-checkpoint.ipynb
./notebooks/.ipynb_checkpoints/goea_nbt3102_fncs-checkpoint.ipynb
./notebooks/.ipynb_checkpoints/goea_nbt3102_group_results-checkpoint.ipynb
./notebooks/.ipynb_checkpoints/goea_sorting-checkpoint.ipynb
./notebooks/.ipynb_checkpoints/relatonships_in_the_go-checkpoint.ipynb
./notebooks/.ipynb_checkpoints/report_depth_level-checkpoint.ipynb
./notebooks/.ipynb_checkpoints/semantic_similarity-checkpoint.ipynb
./notebooks/annotation_coverage.ipynb
./notebooks/cell_cycle.ipynb
./notebooks/goea_nbt3102.ipynb
./notebooks/goea_nbt3102_all_study_genes.ipynb
./notebooks/goea_nbt3102_fncs.ipynb
./notebooks/goea_nbt3102_group_results.ipynb
./notebooks/goea_sorting.ipynb
./notebooks/relatonships_in_the_go.ipynb
./notebooks/report_depth_level.ipynb
./notebooks/semantic_similarity.ipynb
```

**Comment by dvklopfenstein** [comment]
Is it this one:

notebooks/relatonships_in_the_go.ipynb

??

**Comment by jeffsmith8** [comment]
it was actually this one:
https://link.springer.com/protocol/10.1007/978-1-4939-3743-1_16
has the xml functionality been removed? I noticed that in the github notebooks I've followed o far, they have retrieved info from ncbi, not quickgo.

**Comment by dvklopfenstein** [comment]
Dr. Warwick Vesztrocy wrote the items you showing your link. He is a valued contributor and an important co-author. He should be better able to help you since the notebooks that you are referencing are not in this repo.

Thank you very much for your interest in GOATOOLS. If you have comments about a Jupyter notebook in this repo, we can definitely help you. Please include a link to the notebook if you open a new issue.

I am going to close this issue since the Jupyter notebook of interest is elsewhere. @alex-wave, can you help this researcher?

**Comment by dvklopfenstein** [comment]
Dear Dr. Smith,

Thank you for your interest in GOATOOLS and taking the time to write to us.

I see that the QuickGO website is now up. Although this is not a GOATOOLS issue, I do see that you can download GO information using json, rather than XML.

Json can be preferable to XML, so this hopefully can be good news for your situation. The url to download the GO in the example is:

**https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0003723/complete**

You can find an example in a newly added GOATOOLS test:
goatools/tests/test_quickgo_json.py

**Comment by jeffsmith8** [comment]
Thanks for looking into it, I hope to look into it soon!

**Comment by alex-wave** [comment]
Hi @jeffsmith8, thank you for alerting us to this issue and apologies for not getting back to you sooner. As @dvklopfenstein said the OBOXML format has been deprecated by the EBI for QuickGO. I have updated the exercises for the chapter, please see the link from http://gohandbook.org/ or https://github.com/DessimozLab/go-handbook

For further issues with the chapter from the GO handbook, please raise an issue here as this is not related to the GOATOOLS package: https://github.com/DessimozLab/go-handbook/issues
