### ISSUE TITLE
add function to gaf_reader.py - how to get complete gaf files annotations?

### ISSUE THREAD

**Issue by risserlin** [tanghaibao/goatools#125]
Hi, 
I am not sure if there is a different way to do this but I am interested in getting all the annotations from gaf file and not just the mappings from geneids to goids (or vice versa).

I added the following function toe the gaf_reader.py file 
def read_associations(self, **kws):
      return self.associations #return all the associations

To get the complete annotations I then use - 
gafreader = GafReader(gaf_filename, hdr_only = false, prt=sys.stdout)
associations = gafreader.read_associations()

Is there another way to do this?  If not can this function be added to gaf_reader.py?

Thanks, 
Ruth

**Comment by dvklopfenstein** [comment]
Ruth,

Thank you so much for your interest in GOATOOLS and taking the time to write us.

Do you have a preferred GAF file that you are working with?

Your idea is a great one. We might already have what you need. The gaf file is read by the GafReader instance and stored in a data member called, associations, which is a list of namedtuples. Each namedtuple contains one line of information from the gaf file

Would this work for you? The last two lines show printing of all gaf data in all gaf lines:

```
import os
import sys
from goatools.anno.gaf_reader import GafReader

REPO = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")

def test_gaf(prt=sys.stdout):
    """Test finding and reporting illegal GAF lines seen in the field."""
    fin_gaf = os.path.join(REPO, 'goa_human.gaf')
    gafobj = GafReader(fin_gaf, hdr_only=False, prt=prt)
    id2gos = gafobj.read_gaf()  # Read associations
    for ntd in gafobj.associations:
        print(ntd)
```

**Comment by risserlin** [comment]
Perfect.  Thanks!  That is exactly what I was looking for.  Sorry, I am a python newbie.

One other question, I want to get the GO ontology using is_a and part_of and I have figured out how to get is_a (default) and I have also used get_all_upper() to get all the parents using all relationships but is there a way to return the go tree with just is_a and part_of excluding the regulation type terms?

Thanks, 
Ruth

**Comment by dvklopfenstein** [comment]
Welcome to Python! It is a great language.

I added documentation so if other researchers want to access the GAF lines that are stored in the list of namedtuples, they will know that they exist and are easily accessible.

Check out the new Jupyter notebook: 
https://github.com/tanghaibao/goatools/blob/master/notebooks/annotations_gaf_file.ipynb

Can you open a new issue to ask about the GO ontology is_a and part_of?

Thank you again for your interest in GOATOOLS and taking the time to write us.
