### ISSUE TITLE
Enrichment in single GO catetory/scope of multiple test correction

### ISSUE THREAD

**Issue by BrianLohman** [tanghaibao/goatools#127]
Hi,

I'm interested in testing for enrichment in the Biological Processes category only. After digging around a bit in go_enrichment.py it's not obvious how to do this. Is this possible? 

Alternatively, if the multiple test correction is applied only within each of the 3 major GO categories, then this is not an issue as I can just ignore CC and MF. However, if multiple test correction is applied within the three major GO categories or across all three at once (costing me significance for tests I'm not interested in) is also not clear.

Thanks,

Brian

**Comment by dvklopfenstein** [comment]
Brian,

Thank you so much for your interest in GOATOOLS and for taking the time to write us.

You have a great suggestion. And you are correct that the multiple test correction is applied across all three at once. 

Are you running the enrichment from the find_enrichment script or are you calling functions from your own script?

Thank you again for writing us. What you suggest will definitely be of interest to other users.

**Comment by BrianLohman** [comment]
Hi DV, 

Thanks for your quick reply and for the clarification. 

At present I am following one of your examples:  https://github.com/tanghaibao/goatools/blob/master/notebooks/goea_nbt3102.ipynb as closely as possible but swapping mouse for human. I poked around the repo and guessed that the find_enrichment.py script would be a good place to seek answers regarding the scope of enrichment testing and application of multiple testing correction. 

It would be super helpful to be able to run only one GO category at at time. I will try selecting only the GO IDs related to BP from the uncorrected results and then apply the multiple testing correction to just them. I would wager there is a faster way that uses the existing machinery you have built but I am not sure what that might be.  

Cheers,

Brian

**Comment by cross12tamu** [comment]
I have no intention to derail this issue, as I'm very interested in what will occur with the multiple testing correction methodology for GOATOOLS, but...

does PANTHERdb do its' multiple test corrections with one GO category at a time, for "over-representation"/enrichment test? 

Hopefully this is not off-putting or anything! 

Thanks,
Curtis

**Comment by dvklopfenstein** [comment]
@BrianLohman , I am looking at this now. We read both GAF files and gene2go files and need to read the different file formats into namedtuples of similar formats so any new functions will work for both file formats. So there is a little refactoring that must be done to accommodate this. On the plus side, doing the refactoring will help to address https://github.com/tanghaibao/goatools/issues/119.

So addressing your open issue is certainly worth doing now. Also, you have a great request.

@cross12tamu , thank you for your interest in GOATOOLS and following the project. I do not know if PANTHERdb does this. I would guess they did, but do not know for sure. I've got my hands full with these latest issues, so will not have time to look into it.

Thank you both for your great ideas and comments.

**Comment by dvklopfenstein** [comment]
Thank you so much for your interest in GOATOOLS and taking the time to write concerning this important issue.

I have modified the **scripts/find_enrichment.py** script now runs one enrichment analysis per branch.

If you wanted to do this from a script, it would look like this:
Also seen in the updated Jupyter notebook, [**goea_nbt3102.ipynb**](https://github.com/tanghaibao/goatools/blob/master/notebooks/goea_nbt3102.ipynb)

```
from goatools.obo_parser import GODag
from goatools.anno.genetogo_reader import Gene2GoReader
from goatools.goea.go_enrichment_ns import GOEnrichmentStudyNS

from goatools.test_data.genes_NCBI_10090_ProteinCoding import GENEID2NT as GeneID2nt_mus

objanno = Gene2GoReader("gene2go", taxids=[10090])
ns2assoc = objanno.get_ns2assc()
goeaobj = GOEnrichmentStudyNS(
        GeneID2nt_mus.keys(), # List of mouse protein-coding genes
        ns2assoc, # geneid/GO associations
        GODag("go-basic.obo"), # Ontologies
        propagate_counts = False,
        alpha = 0.05, # default significance cut-off
        methods = ['fdr_bh']) # defult multipletest correction method
goea_results_all = goeaobj.run_study(geneids_study)
```

The results in the list of namedtuples, **goea_results_all**, are the three GOEA result lists (one for each of BP, MF, anc CC) concatenated together.

**Comment by dvklopfenstein** [comment]
Thank you for your excellent request and taking the time to contact us. Your request has been added to GOATOOLS. Please give it a try. The new functionality is documented at: [find_enrichment script docs](https://github.com/tanghaibao/goatools/blob/master/doc/md/README_find_enrichment.md#3-limit-the-goea-to-biological-process-molecular-function-andor-cellular-compartment) and the Python notebook is updated to include your request at https://github.com/tanghaibao/goatools/blob/master/notebooks/goea_nbt3102.ipynb

With the addition of this new code, this issue should be fullfilled, so we will close this issue.

**Comment by BrianLohman** [comment]
Hi DV,

Thanks for your quick responses and for addressing my issue. I'll give this a try and let you know if I encounter any further problems. 

Cheers,

Brian
