### ISSUE TITLE
Fetching Descendant Counts

### ISSUE THREAD

**Issue by cross12tamu** [tanghaibao/goatools#129]
I am wondering if there is a function/method already defined somewhere that I can use to fetch the descendant values for a list of GO terms. 
* I have a several numpy arrays where I want to iterate through them and return the descendant value for each GO term. Is this possible?

I am currently unable to find where that method/function is, if it currently exist. Just point me in the right direction if you guys have already written something that does that!

Been really loving GOATOOLS!

Thanks in advance!

Curtis

**Comment by dvklopfenstein** [comment]
Hello Curtis,

Thank you very much for opening this issue. We do indeed calculate the _descendants count_ in the code base. 

I have added a Jupyter notebook which shows how to access and print the _descendants count_ here:

https://github.com/tanghaibao/goatools/blob/master/notebooks/descendants_count.ipynb

**Comment by cross12tamu** [comment]
Awesome stuff, thank you!
