### ISSUE TITLE
Read all GO terms in gaf file, and not just BP terms. 

### ISSUE THREAD

**Issue by datduong** [tanghaibao/goatools#131]
Hi, I am opening a new issue relating to this request https://github.com/tanghaibao/goatools/issues/75#issuecomment-505065958. 

Is possible to read all GO terms not just BP ? For example, in the read_gaf, there is a namespace="BP", is possible to have an option namespace="all" ? 

Thanks.

**Comment by dvklopfenstein** [comment]
Hello @datduong,

Thank you for taking your time to open this issue. We have this functionality, but accessing it certainly could be more user-friendly.

Now, if you add an argument, ***namespace=all***, to ***read_gaf*** or any of the annotation readers function, ***get_id2gos***, you will get all namespaces (BP, MF, CC) in one id2go dict. 

```
from goatools.base import get_godag
from goatools.anno.factory import get_objanno

godag = get_godag('go-basic.obo')

id2gos_ncbi = get_objanno('gene2go', taxid=9606).get_id2gos(namespace='all')
id2gos_gaf = get_objanno('goa_human.gaf').get_id2gos(namespace='all')
id2gos_gpad = get_objanno('goa_human.gpad', godag=godag).get_id2gos(namespace='all')
id2gos_orig = get_objanno('data/association', 'id2gos', godag=godag).get_id2gos(namespace='all')
```

**Comment by datduong** [comment]
Great, thanks for the quick reply. I will close issue.
