### ISSUE TITLE
Input files    

### ISSUE THREAD

**Issue by Caro-Ca** [tanghaibao/goatools#140]
Hi!
I've got a tsv file from the Interproscan annotation and I am converting it into a txt file. However, I am noticing that some of my genes don't have a GO term. Should I delete those genes that don't map to a go term? I also have duplicates, but I deleted those duplicates. Hope I'm doing correctly.

On the other hand, I am working with Rosellinia necatrix_. The information I got is from a de novo genome assembly. However,  I don't understand why we do a population, study and association file.

Thank you in advance for your help.

**Comment by dvklopfenstein** [comment]
Hello @Caro-Ca ,

Thank you for your interest in GOATOOLS and for taking the time to write us.

Yes, just delete those genes that do not have a GO term annotated to it. 

# Files
## Association file
The association file associates genes or gene products to GO terms, so you will defintely need this file. What is the format of the Interproscan annotations? If it is not GAF or GPAD and you are converting it to a text file, you will need to convert it to a format shown in this example:

https://github.com/tanghaibao/goatools/blob/master/data/association.txt

This format has one line per gene. The gene name is first, then a tab, then a list of GO IDs separated by semi-colons. This is one of the annotation formats that we can read. Researchers with non-model organisms often use this format if there is no gaf or gpad format available.

## Study and Population files
The study and population files are lists of genes, with one gene per line.

The population file contains the full list of genes in the organism or in your experiment.

The study file contains a subset of the genes in the population file. These are often genes that are up-or-down-regulated in an experiment or stand out from the population in some other way.

During enrichment analysis the annotations of the annotations of the genes in the study set are compared to the annotations of the genes in population set. If the ratio of the annotations for each set are much different, then the gene enrichment analysis will report this.

**Comment by Caro-Ca** [comment]
Thank you for replying, but I got an error. I've cut a small section of the entire file to check if the code runs perfectly. However, this is what I got: 
```
~/goatools/scripts$ python go_plot.py -i test.txt
Traceback (most recent call last):
  File "go_plot.py", line 16, in <module>
    run()
  File "go_plot.py", line 12, in run
    PlotCli().cli()
  File "/home/edgar/anaconda2/lib/python2.7/site-packages/goatools/cli/gosubdag_plot.py", line 192, in cli
    go2obj = GODag(kws_all['obo'], optional_attrs)
  File "/home/edgar/anaconda2/lib/python2.7/site-packages/goatools/obo_parser.py", line 310, in __init__
    self.version = self.load_obo_file(obo_file, optional_attrs, load_obsolete, prt)
  File "/home/edgar/anaconda2/lib/python2.7/site-packages/goatools/obo_parser.py", line 314, in load_obo_file
    reader = OBOReader(obo_file, optional_attrs)
  File "/home/edgar/anaconda2/lib/python2.7/site-packages/goatools/obo_parser.py", line 53, in __init__
    "go-basic.obo]".format(OBO=obo_file))
Exception: COULD NOT READ(go-basic.obo)
download obo file first
 [http://geneontology.org/ontology/go-basic.obo]

```
This is how the file looks like: 
```
~/goatools/scripts$ less test.txt
IPR036852       GO:0004252;GO:0006508
IPR000209       GO:0004252;GO:0006508
IPR000048       GO:0005515
IPR008936       GO:0007165
IPR001936       GO:0043087
IPR001715       GO:0005515
IPR000593       GO:0005515
IPR002173       GO:0016773
IPR034093       GO:0004454;GO:0006000
IPR034812       GO:0016491
IPR010255       GO:0004601;GO:0006979;GO:0020037;GO:0055114
IPR017972       GO:0016705;GO:0055114
IPR011545       GO:0003676;GO:0005524
IPR030381       GO:0005525
IPR000375       GO:0005525
IPR001401       GO:0003924;GO:0005525
IPR002509       GO:0005975;GO:0016810
IPR011330       GO:0003824;GO:0005975
IPR027786       GO:0005634;GO:0006281;GO:0030915
IPR007320       GO:0005737
IPR006885       GO:0016651;GO:0022900
IPR002401       GO:0005506;GO:0016705;GO:0020037;GO:0055114
IPR002938       GO:0071949
IPR002937       GO:0016491;GO:0055114
IPR001613       GO:0016491;GO:0055114
IPR026635       GO:0008168
IPR009548       GO:0003725
IPR004598       GO:0000439;GO:0001671;GO:0006289
IPR010636       GO:0005576
IPR036686       GO:0005576
IPR002129       GO:0016831;GO:0019752;GO:0030170
IPR021115       GO:0016831
IPR017946       GO:0006629;GO:0008081
IPR030395       GO:0006629;GO:0008081
IPR001765       GO:0004089;GO:0008270
IPR036874       GO:0004089;GO:0008270
IPR014851       GO:0034551
IPR003959       GO:0005524
IPR027243       GO:0034551
IPR005630       GO:0000287;GO:0010333;GO:0016829
IPR013155       GO:0004812;GO:0006418
IPR002302       GO:0000166;GO:0004823;GO:0005524;GO:0006429
IPR025709       GO:0002161;GO:0006418
IPR009080       GO:0000166;GO:0004812;GO:0005524;GO:0006418
IPR001412       GO:0000166;GO:0004812;GO:0005524;GO:0006418
IPR009008       GO:0002161;GO:0006418

```

**Comment by dvklopfenstein** [comment]
Download the go-basic.obo file:

```
$ wget http://geneontology.org/ontology/go-basic.obo
```

**Comment by Caro-Ca** [comment]
Now it is working, but it is strange because I already did it at the beginning as it was the first step of the installation process. Thank you, anyway.

**Comment by dvklopfenstein** [comment]
@Caro-Ca , I am so glad that it is working for you now.  Thank you for your interest in GOATOOLS.
