### ISSUE TITLE
NCBI annotations: Use get_ns2assc() to combined species annotations

### ISSUE THREAD

**Issue by tanghaibao** [tanghaibao/goatools#147]
Received via direct email
--
Dear,
I am using Goatools but I have a question. I am doing your notebook https://github.com/tanghaibao/goatools/blob/master/notebooks/goea_nbt3102.ipynb but in  objanno = Gene2GoReader(fin_gene2go, taxids=[10090])
I need work with all taxid and for this I run objanno = Gene2GoReader(fin_gene2go, taxids=TRUE)  and it works well, but the next step ns2assoc = objanno.get_ns2assc() doesn't work for me, the error says :
AssertionError: **FATAL: TAXID(None) DATA MISSING

How can I work that tutorial with all the taxid?
Thanks in advance,
Paz

**Comment by dvklopfenstein** [comment]
I will take a look at this. My schedule is a bit tight for about a week until after the New Year, starting Jan 3rd, so it may need to wait until then.

Thank you for your interest in GOATOOLS and taking the time to write us regarding on this issue.

**Comment by ptapiar** [comment]
any solution for this error?

**Comment by dvklopfenstein** [comment]
I will look at this this week and get back to you by Monday. Thank you for your patience.

**Comment by dvklopfenstein** [comment]
@ptapiar , Thank you for the great question regarding working with multiple taxids loaded by the NCBI annotation reader, Gene2GoReader.

I have documented the augmented functionality of get_ns2assc() in a new 
[Python notebook](https://github.com/tanghaibao/goatools/blob/master/notebooks/annotations_ncbi_gene2go.ipynb)

If only one taxid is loaded into Gene2GoReader, then you call get_ns2assc() with no arguments. Or if you do specify a taxid argument, it is ignored.

If more than one taxid is loaded into Gene2GoReader, then the taxid argument in get_ns2assc(taxid) must be specified by the user. The taxid value can be any of:

| taxid               |  return
|----------------|-----------------------
| **int**            | ns2assc for just the species specified by taxid
|**List of ints** | ns2assc for the combined species specified by the taxid list
|**True**          | ns2assc containing all species genes

Thanks again for the terrific question. Check it out and let me know what you think and if it suits your needs. I decided to make the taxid argument required if multiple species are loaded so the researcher may be warned that the association is unusual in that it contains many species.
