### ISSUE TITLE
map_to_slim.py error

### ISSUE THREAD

**Issue by yuanning-li** [tanghaibao/goatools#152]
Hey, I got an errorr when I was trying to map my whole list of go terms to go slim. Would you mind taking a look at this error? I know multiple people got this error and not sure it is a bug or something.

**ERROR IdToGosReader(..., godag=None).get_id2gos: GODAG is None. IGNORING namespace(BP)

Best,
Li

**Comment by AstrobioMike** [comment]
Hiya, folks, 

Thanks for GOATools :) 

I'm hitting the same error while trying to use map-to-slim. Is any more known about this?

**Comment by AstrobioMike** [comment]
I'll just note for any others that might come through here that of the conda-installable versions, 0.8.12 is the latest version that does not through the error, but the next available there, 0.9.5, does. That said, the outputs seem to be the same regardless of the error.

**Comment by tanghaibao** [comment]
This is not an error and as noted here it should not impact results.
I did change the messaging from "ERROR" to "WARNING" instead and a friendlier message to the user:

> WARNING:root:IdToGosReader.get_id2gos: GODAG is None. IGNORING namespace(BP). If you are running `map_to_slim.py`, this warning can be ignored.
