### ISSUE TITLE
Retrieve "consider" key of the obsolete GO terms AttributeERROR

### ISSUE THREAD

**Issue by AgustinPardo** [tanghaibao/goatools#154]
Hello,

I am parsing the go.obo file by:

> obodag = GODag("go.obo", load_obsolete=True)

I am having problems trying to capture the "consider" key of the GO terms that are obsoletes in the go.obo file.

For example this term:

> [Term]
> id: GO:0000067
> name: obsolete DNA replication and chromosome cycle
> namespace: biological_process
> def: "OBSOLETE. (Was not defined before being made obsolete)." [GOC:ai]
> comment: This term was made obsolete because it has been superseded by more accurate terms to represent the biological processes occurring, and it is not clear that this term represents a useful entity.
> synonym: "DNA replication and chromosome cycle" EXACT []
> is_obsolete: true
> consider: GO:0006260
> consider: GO:0007059
> consider: GO:0051276

So I try:

> obodag["GO:0000067"].is_obsolete
> True 

That is ok, so I try this and I get an error:

> obodag["GO:0000067"].consider
> AttributeError: 'GOTerm' object has no attribute 'consider'

How could I get the "consider" information of the terms?

Regards

**Comment by dvklopfenstein** [comment]
Thank for taking the time to open this issue. The optional attributes *consider* and *replaced_by* were not supported by GOATOOLS, so I have added support as well as adding some speed improvements when loading optional attributes.

Thank you for requesting this new feature, it will surely be useful to other researchers. As soon as the regression tests pass, I will ask @tanghaibao to release a new version of GOATOOLS which contains this new functionality. The new functionality is also available immediately using *git clone.*

**Comment by dvklopfenstein** [comment]
I added a Jupyter notebook showing how to load and work with obsolete GO terms, including accessing the optional attributes, *consider* and *replaced_by*.

https://github.com/tanghaibao/goatools/blob/master/notebooks/godag_obsolete_terms.ipynb

Thank you so much for the great questions.

**Comment by tanghaibao** [comment]
@dvklopfenstein 

New release at `v1.0.2`.

**Comment by AgustinPardo** [comment]
Wonderful! I appreciate the great commitment.
