### ISSUE TITLE
Remove GODag command output

### ISSUE THREAD

**Issue by AgustinPardo** [tanghaibao/goatools#155]
Hello,

Do you know how to remove the output of this command?

command:
`obodag=GODag("go.obo", optional_attrs={'consider', 'replaced_by'}, load_obsolete=True) `
output:
`go.obo: fmt(1.2) rel(2019-10-07) 49,992 GO Terms; optional_attrs(consider replaced_by)`

Regards

**Comment by dvklopfenstein** [comment]
Hello!

Set argument, `prt=None` like this:

```
godag = GODag(fin_dag, optional_attrs={'consider', 'replaced_by'}, load_obsolete=True, prt=None)
```

I have updated the Jupyter notebook to demonstrate this.

**Comment by AgustinPardo** [comment]
Thanks from Argentina!
