### ISSUE TITLE
mismatch between go.values and get_all_children 

### ISSUE THREAD

**Issue by mdanb** [tanghaibao/goatools#160]
I am using the go-basic.obo file. When I do `len(go.values())`, I get 47245. Note that the GO terms below are for BP, CC, AND MF. When I do `len(go["GO:0003674"].get_all_children()) + len(go["GO:0005575"].get_all_children()) + len(go["GO:0008150"].get_all_children())` I instead get 44576. Since the graphs are separate, these values should be only separated by 3 (corresponding to the terms for BP, CC, and MF). Why are they not matching?

**Comment by tanghaibao** [comment]
@mdanb 

I know it is a year too late for a response but I just did a quick analysis to investigate the discrepancy that you found, and added my analysis to our [report_depth_level notebook](https://github.com/tanghaibao/goatools/blob/main/notebooks/report_depth_level.ipynb).

Long story short, the numbers match exactly if you remove duplicates with `set(go.values())`. The reason for the duplicates is that some of the entries have **alternative_id**. For example, [GO:0003887](https://salivaryproteome.nidcr.nih.gov/public/index.php/Special:Ontology_Term/GO:0003887) contains 16 alternative ids, which led to the duplicates, i.e. you are getting the same term back when you do `GO:0016448`, `GO:0016449` etc.) - causing the inflation in total counts that you saw.

Haibao
