### ISSUE TITLE
**FATAL: NO POPULATION ITEMS SEEN IN THE ANNOTATIONS

### ISSUE THREAD

**Issue by HLAvieira** [tanghaibao/goatools#165]
Hello, I thank the authors very much for making goatools available for the scientific community. Right now I'm struggling with GOEA from the command line (Windows 10). I got my study genes identifiers [st2synchr3_sc.txt](https://github.com/tanghaibao/goatools/files/4625469/st2synchr3_sc.txt) from an NCBI chromosome annotation and my population background [all_sc_genes.txt](https://github.com/tanghaibao/goatools/files/4625462/all_sc_genes.txt) from Biomart Ensembl (all _Saccharomyces cerevisiae_ genes). I'm also using GPAD as an association entry from SGD
After I run the command:
`C:\>find_enrichment.py C:\Biopyhton_files\st2synchr3_sc.txt C:\Biopyhton_files\all_sc_genes.txt C:\Users\Hugo\Documents\Meus_projetos\Biopython_Studies\Gene_ontology\sgd.gpad --pval=0.05 --method=fdr_bh --pval_field=fdr_bh --outfile=results_gpad.xlsx`
I get the following output: 
![Capture_fatal_goatools_fe](https://user-images.githubusercontent.com/61484911/81879430-2bf40480-9561-11ea-89ef-395f0fdeb861.PNG)

So I can see that the number of genes is correct both in the study and in the population files, although I face the ****FATAL: NO POPULATION ITEMS SEEN IN THE ANNOTATIONS**

When I use another tool for GOEA, as the online web service [LAGO](https://go.princeton.edu/cgi-bin/LAGO), enrichment results are seen as below if (and only if) I paste both the study genes and the population genes as plain text, one per line:
![lago_results](https://user-images.githubusercontent.com/61484911/81880728-8d69a280-9564-11ea-8e0a-063867ddeadd.PNG)
Interestingly, if I use the same data, but from .txt files, there are no genes associated with any GOIDs. Thus, it's possible that my .txt files are somehow incorrect, but I really don't see how this is possible.

**Comment by dvklopfenstein** [comment]
Thanks for the detailed and easy instructions showing how to duplicate your issue. I am seeing the same error messages that you are and am looking into it....

**Comment by HLAvieira** [comment]
Thank you very much for the support

**Comment by dvklopfenstein** [comment]
It looks like a name issue. The names used in the association, in sgd.gpad, are using the **SGI ID**. But the names in the population, in all_sc_genes.txt, are using the **Systematic Name**.

If you can convert the names in your study file and population file from the **Systematic Name** to the **SGI ID**, it should work. Do you have a way to convert them?

![goatools_i165](https://user-images.githubusercontent.com/7278188/81884324-9149f480-9565-11ea-9a03-756b02d1d1c2.png)

**Comment by dvklopfenstein** [comment]
I wrote SGD's help desk asking about converting yeast IDs at  sgd-helpdesk@lists.stanford.edu.

We will see what they say. Here is a copy of the email:
Hello,

Thank you so much for your amazing database and the associated tools.

I am truing to convert SGI IDs (like SGD:S000002795) to the Systematic Name (like YDR387C) and thought the API might be a good way to do this.

I tried your API example, but received "Failed to Fetch" for the following tries:
curl -X GET "http://www.yeastgenome.org/backend/locus/YDR387C" -H "accept: application/json"
curl -X GET "http://www.yeastgenome.org/backend/locus/S000002795" -H "accept: application/json"
curl -X GET "http://www.yeastgenome.org/backend/locus/SGD%3AS000002795" -H "accept: application/json"

How might I convert these IDs? What sort of information needs to be in the locusId field to run the API?

Thank you very much for your time.

Regards,

DV

**Comment by HLAvieira** [comment]
Once again I thank for your help. I'll try to convert the systematic name to SGD ID and also await for the SGD help desk response. 

Best regards,
Hugo Vieira

**Comment by dvklopfenstein** [comment]
I haven't heard back from them yet. They would be the source for that answer. If you find out how to convert those IDs, please post it here.

**Comment by HLAvieira** [comment]
Hello,
I found out that the  [SGD web site](https://www.yeastgenome.org/) has a very straightforward way to convert those IDs through the [Gene Lists menu](https://yeastmine.yeastgenome.org/yeastmine/bag.do). We simply upload our list with the systematic names and then choose to export the data we want as .tsv (in my case I've only selected the SGD IDs).

After converting the population file to [all_sc_sgd_id.txt](https://github.com/tanghaibao/goatools/files/4648294/all_sc_sgd_id.txt) and the study file to
[synchr3_sgd_id.txt](https://github.com/tanghaibao/goatools/files/4648295/synchr3_sgd_id.txt) I proceeded to run the code once again and didn't face any errors.
Unfortunately, my data didn't result in any enriched GOIDs, but I had the same results for those SGD IDs when pasting them or uploading those files in  [LAGO](https://go.princeton.edu/cgi-bin/LAGO). Maybe there's an inconsistency in SGD IDs in comparison to systematic, but I'll keep learning to use GOATOOLS.

Once again I thank you, DV, for all the help.
I'll keep this issue open for the next 24h in case someone has any additional comments.

Truly,
Hugo Vieira
