### ISSUE TITLE
p-value calculation discrepancy 

### ISSUE THREAD

**Issue by jvivian-atreca** [tanghaibao/goatools#166]
Greetings and thank you for all the work on this tool!

I noticed in several cases I am unable to recapitulate the same uncorrected p-value generated by GOAtools. Given that I get the same p-value *sometimes*, I am confused where this discrepancy is occurring. I thought it might have to do with `propagate_counts`, but it happens whether or not it's set to `True` or `False`.

Here's an example of results I get from GOATools:

ratio_in_study | ratio_in_pop | p_uncorrected
-- | -- | --
9/1358 | 17/21733 | 2.17564E-07
9/1358 | 18/21733 | 4.10921E-07
30/1358 | 157/21733 | 4.46535E-07

I copied [this function](https://github.com/tanghaibao/goatools/blob/3489301efd4a41e22b8f914caf344e5248ef811b/goatools/pvalcalc.py#L42-L74) for calculating p-values and here are my results — the first two match but the last one does not:

```
In [71]: fisher_pcalc(9, 1358, 17, 21733)
Out[71]: 2.175636982797983e-07

In [72]: fisher_pcalc(9, 1358, 18, 21733)
Out[72]: 4.1092116455329316e-07

In [73]: fisher_pcalc(30, 1358, 157, 21733)
Out[73]: 3.5420075774639804e-08
```

When there is an inconsistency, the p-value calculated from the function is always smaller than the `p_uncorrected` that's reported.

**Comment by tanghaibao** [comment]
Late response to the OP. A potential discrepancy of uncorrected P-value could be due to the difference in using `fisher` and `scipy.stats.fisher_exact`, as reported also in #168. 

In light of this discrepancy and potentially buggy results from `fisher`, we have removed using `fisher` altogether from `goatools`.
