### ISSUE TITLE
conda install goatools fails on win64 with nvidia gpu

### ISSUE THREAD

**Issue by simonwm** [tanghaibao/goatools#168]
Tried to install goatools using conda, but get a weird incompatibility message:

> Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining @/win-64::__cuda==10.2=0:  67%|████████████████████████████████                | 2/3 [00:01<00:00,  3.58it/s]-Examining conflict for __cuda:  67%|███████████████████████████████████▎                 | 2/3 [00:00<00:00, 17.25it/s]\failed
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your CUDA driver:
>   - feature:/win-64::__cuda==10.2=0
>   - feature:|@/win-64::__cuda==10.2=0
> Your installed CUDA driver is: 10.2

I get it using a completely new conda environment with python 3.6, 3.7, 3.8. I did not have this problem with conda on Linux without GPU. As afaik goatools does not make use of GPU acceleration, I guess that the error message does not really have much to do with the GPU - somehow it still shows up.

If I use `pip install goatools` instead of `conda install goatools` it works fine. So it has to be something wrong with the conda package on Windows (if there is an Nvidia GPU present). A similar bug was solved for another package [here](https://github.com/KevinMusgrave/pytorch-metric-learning/issues/55#issuecomment-629698723). Maybe that fix could work here, too?

**Comment by djdidao233** [comment]
I encountered the same error and can't install jupyter.
![image](https://user-images.githubusercontent.com/44863045/86525231-1ba03c00-beb7-11ea-9aa0-a560cb310e8a.png)

![image](https://user-images.githubusercontent.com/44863045/86525228-0a572f80-beb7-11ea-944c-cd6e133cdf0a.png)

I can't find the answer in the community.

![image](https://user-images.githubusercontent.com/44863045/86525292-d6303e80-beb7-11ea-9d0b-5118399d3b2d.png)

**Comment by adivyas101** [comment]
I'm having the same issue while installing keras and tensorflow using conda package. I think it might have to do with my python 3.8 version. However, using pip command I can install both keras and tensorflow. Nonetheless, even after that my keras is not working and I can not import it in my jupyter notebook. 

````
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining @/win-64::__cuda==10.2=0:  67%|████████████████████████████████                | 2/3 [00:05<00:02,  2.74s/it]/failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/win-64::__cuda==10.2=0
  - feature:|@/win-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2`
```
