### ISSUE TITLE
uncorrected p-value methods give different results 

### ISSUE THREAD

**Issue by emilyyaklich** [tanghaibao/goatools#169]
Hi - thank you for creating this tool! It has been very helpful for me. 

I have noticed that I am getting very different p-value results when using the fisher's package test vs. when using the SciPy Stats test for calculating the uncorrected p-values.

For example, when using the fisher package I get the following result:
 

GO | name | ratio_in_study | ratio_in_pop | p_uncorrected
-- | -- | -- | -- | --
GO:0009058 | biosynthetic process | 1485/4830 | 3026/13353 | 1E-05

where the uncorrected p-value is **1E-05**.

and when using the SciPy test on the same data I get this result: 

GO | name | ratio_in_study | ratio_in_pop | p_uncorrected
-- | -- | -- | -- | --
GO:0009058 | biosynthetic process | 1485/4830 | 3026/13353 | 1.2E-61

where the uncorrected p-value is **1.2E-61**.

Based on the documentation, I was under the impression that the two methods should calculate the same p-values, so I was just wondering if you might have any insight into why I am getting different results based on the different methods?

Thank you!

Emily

**Comment by tanghaibao** [comment]
@emilyyaklich 

In this case, the scipy p-value seems to be correct (R generates the same answer). The fisher implementation has an underflow issue that lost precision.

@dvklopfenstein 

I'll see if I can fix fisher, but we might need to consider using the default FET implementation in scipy, if not already.

Haibao
