### ISSUE TITLE
GoaTools error ? (python plot_go_term.py --term=GO:0005737 --gml )

### ISSUE THREAD

**Issue by sunnykevin19** [tanghaibao/goatools#172]
HI,
I'm data analysis using GoaTools, I installed all the sufficient packages, its shows error. Not able to figure it out. Help is needed. Using Python 3.7.6

python plot_go_term.py --term=GO:0005737 --gml 
go-basic.obo: fmt(1.2) rel(2020-06-01) 47,233 GO Terms
GO:0005737  level-02    depth-02    cytoplasm [cellular_component]
all parents: {'GO:0005575', 'GO:0110165'}
all children: {'GO:0016528', 'GO:0099631', 'GO:0106037', 'GO:0045495', 'GO:0060293', 'GO:0032838', 'GO:0120111', 'GO:0097575', 'GO:1902716', 'GO:0061846', 'GO:1990753', 'GO:1904115', 'GO:0099568', 'GO:0051285', 'GO:0097014', 'GO:0098831', 'GO:0032839', 'GO:0099738', 'GO:0045179', 'GO:0061803', 'GO:0061802', 'GO:0045180', 'GO:1990917', 'GO:0005938', 'GO:0031097', 'GO:0098834', 'GO:1904269'}
Traceback (most recent call last):
  File "plot_go_term.py", line 59, in <module>
    draw_children=opts.draw_children)
  File "/home/cent/anaconda3/lib/python3.7/site-packages/goatools/obo_parser.py", line 594, in draw_lineage
    obj = nx.from_agraph(grph) if engine == "pygraphviz" else nx.from_pydot(grph)
AttributeError: module 'networkx' has no attribute 'from_agraph'

**Comment by tanghaibao** [comment]
Fixed in https://github.com/tanghaibao/goatools/pull/182/. Closing issue.
