### ISSUE TITLE
how to find association_file?

### ISSUE THREAD

**Issue by shiyi-pan** [tanghaibao/goatools#175]
hi,tanghaibao:
I study on soybean, so I don't  how to find the association file .Could  you tell me how to get it.thank you very much.

**Comment by dvklopfenstein** [comment]
Thank you for your interest in GOATOOLS and for taking the time to write us.

It looks like it will take a bit of set up before you can run enrichment analyses. Here is what needs to be done, as far as I can currently see.

## 1. Download annotations
It looks like you can download the soybean annotations from https://www.soybase.org/genomeannotation/ . At the bottom of the page, you can download one file containing all GO annotations to soybean proteins.

## 2. Reformat annotations
The file is a tab-separated list of soybean proteins. Information from that file can be re-formatted to our ID-to-GOs format seen in https://github.com/tanghaibao/goatools/blob/master/data/association.txt. I could write you a sample script Tuesday, if that helps.

## Gene names
Are you using gene names or protein names? The protein IDs in the annotation file look are Glyma IDs, for example Glyma0002s50. If you are using gene names or protein names other than Glyma IDs, you will need scripts to translate one to the other. I am not sure what your IDs look like, so am not sure how much of a job it is.

Getting the scripts set up just needs to be done once, but is a bit of a project.

**Comment by shiyi-pan** [comment]
Thank you for your help. I have download the  annotations and re-formatted it to the ID-to-GOs format. Thank you.
