### ISSUE TITLE
Where to find background_genes_ncbi notebook?

### ISSUE THREAD

**Issue by mcsimenc** [tanghaibao/goatools#176]
Hello,

I would like to see the notebook referenced in the _Run a Gene Ontology Enrichment Analysis (GOEA)_ notebook here:

"Follow the instructions in the background_genes_ncbi notebook to download a set of background population genes from NCBI."

Do you know where I can find this notebook?

Thanks

**Comment by diegoshalom** [comment]
I found it here:
https://notebook.community/tanghaibao/goatools/notebooks/backround_genes_ncbi
