### ISSUE TITLE
What does R represent

### ISSUE THREAD

**Issue by chestnzu1** [tanghaibao/goatools#178]
Hello:
       Currently, I am using go_plot.ply to create a hierarchical graph, I notice inside the rectangle, there are some descriptions like the GOID, the depth, and descendant count, But I can not find the explanation for R. Can you tell me what does 'R' represent? Thanks in advance.

      best,
       Yi

**Comment by dvklopfenstein** [comment]
Hello,

Thank you for your interest in GOATOOLS and thanks for the great question.

**R** is depth when taking into account optional relationships, like *part_of*.

**Depth** is the length of the longest path from the root term, like *cellular_component*, to the term of interest.

So in this plot:

<img src="https://user-images.githubusercontent.com/7278188/94598187-97164d00-025c-11eb-84df-39b178d43f60.png" alt="drawing" width="500"/>

The bottom term's title is:

**GO:0043231 D3 R4 d0**

**D3** means that the longest path from the root, **cellular_component**, to the bottom term is 3 edges, when using **only** the *is_a* required relationships.

**R4** means that the longest path from the root, **cellular_component**, to the bottom term is 3 edges, when using **both** the *is_a* relationships (black arrows) and the optional *part_of* relationships (dashed orange arrows).

**Comment by dvklopfenstein** [comment]
Check out the new section at the top of this Python notebook added to better help other researchers understand **D** and **R**:

https://github.com/tanghaibao/goatools/blob/main/notebooks/get_isa_and_partof.ipynb

Thanks again for the terrific question
