### ISSUE TITLE
cannot export gml file 

### ISSUE THREAD

**Issue by Lix1993** [tanghaibao/goatools#181]
https://github.com/tanghaibao/goatools/blob/85bcc539ffa6eab2022c773fd03a25cd868718a5/goatools/obo_parser.py#L594-L599

`nx` has no `from_agraph` or `from_pydot` methods,
when changed to `nx.nx_agraph.from_agraph` for `nx.nx_pydot.from_pydot`

`nx.write_gml(self.label_wrap, gmlfile)` raises:
`attributeError: 'function' object has no attribute 'is_multigraph'`

**Comment by tanghaibao** [comment]
@Lix1993 

Merged. Thanks for your contribution!
