### ISSUE TITLE
Ancestors considering specific relations

### ISSUE THREAD

**Issue by rashmie** [tanghaibao/goatools#194]
Hi!

Is there a way in goatool that I can retrieve all ancestors considering specific relations like 'part_of'? The reasoning rules mentioned in the following Gene Ontology document should also be considered. 

http://geneontology.org/docs/ontology-relations/

For example, if A is_a B and B part_of C, then A part_of C is inferred.

I could use 'part_of' as an optional relation but that retrieves all 'is_a' only ancestors as well. I think the way it is done right now, 'is_a' relationship is always required and cannot be removed.

**Comment by dvklopfenstein** [comment]
Thank you for your interest in GOA TOOLS and for taking the time to write us.

Yes! you can get the ancestors through either through *is_a* and optional relationships. See how in this notebook:

https://github.com/tanghaibao/goatools/blob/main/notebooks/parents_and_ancestors.ipynb

**Comment by rashmie** [comment]
Thanks for the quick response. However, what I need is to obtain ancestors only considering a specific relationship like part_of. 
For example, consider the following relationships.
A is_a B
A is_a C
A part_of D
B part_of E
D part_of F
D is_a G

Here A's ancestors considering part_of relation are: E, D, G & F.
B & C are not ancestors considering part_of relation according to the reasoning rules I mentioned previously. Right now the way things are, B & C are also obtained.

**Comment by dvklopfenstein** [comment]
Thank you for the clarification. I am about to work on #184 and this question might also fold in nicely to that work.

I will investigate further your question when I work on #184. We do not do this currently. But this a great question and could be useful for other researchers using GOA TOOLS.

Thank you so much for the thoughtful question.

Do you have any more information which might be useful to us in researching and implementing this functionality?

**Comment by rashmie** [comment]
Thanks in advance for working on this. I don't have any additional material regarding this. However, I'm more than happy to be of help any way I can. Feel free to let me know if you have further questions regarding this.

**Comment by dvklopfenstein** [comment]
Thanks for the offer to help. Trying the new functionality out and commenting on the to-be-added notebook would be very helpful.

What is the usage case for your need for this functionality? This could help inform what other researchers would also need this functionality.

Thank you so much for taking your time to write us and thank you for the terrific idea.

**Comment by rashmie** [comment]
We are doing some work to audit the Gene Ontology to identify some quality issues. This requires us to traverse through specific types of relationships as I mentioned.

**Comment by dvklopfenstein** [comment]
Great. Sounds good. Thank you for the feedback. This request sounds extremely useful.

**Comment by rashmie** [comment]
Hi @dvklopfenstein! May be the following issue I opened in the GO helpdesk might be useful for this. 

https://github.com/geneontology/helpdesk/issues/293

It seems the GO relationships documentation that I referred to earlier might not be all accurate.
