### ISSUE TITLE
How can i get def in obo file?

### ISSUE THREAD

**Issue by Lix1993** [tanghaibao/goatools#204]
like this:

```
[Term]
id: GO:0000001
name: mitochondrion inheritance
namespace: biological_process
def: "The distribution of mitochondria, including the mitochondrial genome, into daughter cells after mitosis or meiosis, mediated by interactions between mitochondria and the cytoskeleton." [GOC:mcc, PMID:10873824, PMID:11389764]
synonym: "mitochondrial inheritance" EXACT []
is_a: GO:0048308 ! organelle inheritance
is_a: GO:0048311 ! mitochondrion distribution
```

**Comment by dvklopfenstein** [comment]
Thank you so much for your interest in GOA TOOLs and for taking your time to write us.

I just added a Jupyter notebook to explain how to access the optional attribute, "def" (aka definition or defn).

https://github.com/tanghaibao/goatools/blob/main/notebooks/Optional_attribute_definition.ipynb

Please let us know if the new notebook answers your question adequately.

Thank you so much for this excellent question, which will surely benefit all of the researchers who use GOA TOOLs in their work

**Comment by Lix1993** [comment]
thanks
