### ISSUE TITLE
study (geneIDs) cannot be a numpy array

### ISSUE THREAD

**Issue by wu-diana** [tanghaibao/goatools#214]
Running GOEnrichmentStudyNS.run_study with a numpy array as study (geneIDs) gives the following error: `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

This is caused by lines 299-300 in GOEnrichmentStudyNS` if not study:
                 return []`

I recommend updating `if not study:` to a statement that is flexible for generic iterators.

**Comment by tanghaibao** [comment]
@wu-diana 

Should have been fixed in the commit referenced here. Thanks for the heads up.
