### ISSUE TITLE
Python3 Support

### ISSUE THREAD

**Issue by stuppie** [tanghaibao/goatools#23]
Are there any plans on upgrading to Python3 ?
I ran everything through 2to3 and then manually fixed a couple things and got the obo_parser and mapslim to work correctly. I haven't tested everything else though. Is there any interest in migrating everything to py3?

**Comment by tanghaibao** [comment]
One of the dependencies is ``fisher`` package, which is numerically unstable under py3 (https://github.com/brentp/fishers_exact_test/issues/7). I'd like to wait until that's resolved. Thanks.

**Comment by stuppie** [comment]
Ok. Whenever it is fixed, see: https://github.com/stuppie/goatools
Should be working under py3

**Comment by tanghaibao** [comment]
Thanks for the work. Can you do a pull request? I'll verify the output and get this merged.

**Comment by tanghaibao** [comment]
Greg, I've pulled the changes - seems fine. I'm closing this issue for now. Thanks for contributing - I hope you don't mind getting credited as one of the 'authors'.

**Comment by stuppie** [comment]
Great! Thanks
