### ISSUE TITLE
`log = None` cannot complete suppress stdout in GOEnrichmentStudyNS

### ISSUE THREAD

**Issue by illumination-k** [tanghaibao/goatools#238]
Thanks for the great project!

I want to stop logging completely, but `__init__` function in `GOEnrichmentStudy` has `print` regardless of `log` kwd, so I cannot.

https://github.com/tanghaibao/goatools/blob/d3a63f9738efcdb9f2f49e40cf1fadeb58de9bac/goatools/go_enrichment.py#L256

I think if `log` is None, nothing should be output to stdout.
This is not a so big problem, but not useful when redirecting or something.

**Comment by tanghaibao** [comment]
@illumination-k 

Thank you for the issue report. I added the fix that considered the `log` keyword.

**Comment by tanghaibao** [comment]
@dvklopfenstein 

Longer-term, we could move to using `logging` instead of using `prt` and `log` parameter throughout the code, as suggested in #159.
