### ISSUE TITLE
NOT FOUND IN DAG

### ISSUE THREAD

**Issue by msheltra** [tanghaibao/goatools#246]
I'm trying to run goatools using the command:
/storage/home/mrs97/work/miniconda3/envs/goatools/bin/find_enrichment.py FIF_FIC_down.IDs FIF_FIC_population.txt go_annotations_by_gene.txt --pval=0.05 --method=fdr_bh --pval_field=fdr_bh --outfile=test_id2gos.xlsx
I've gotten it to run with sample files from a friend who has done it before, but when I try to use my own data, I get the error GO:...NOT FOUND IN DAG over and over before it says it isn't writing the outfile and that there are no enrichment results. Any ideas about what this means and how to fix it would be greatly appreciated. Thanks!

**Comment by dieunelderilus** [comment]
hi @msheltra - Please, did you figure out this problem? I am currently facing this same error with my GO enrichment analysis. Please could you let me know how you solved this problem.  I feel that this error affects the results of  this analysis.
Cheers,
~DD

**Comment by msheltra** [comment]
Hello, unfortunately I don't recall how I managed to fix this situation. I know that one thing I tried was making an environment specifically for goatools, which I have in my notes, but I can't remember if this was the element that helped me deal with the DAG issue. Sorry I can't be of more help.

Best of luck,
msheltra


________________________________
