### ISSUE TITLE
Child Term Relationships

### ISSUE THREAD

**Issue by stuppie** [tanghaibao/goatools#25]
It seems that goatools is only considering children that have an "Is a" relationship with their parent, but not a "Part of". It seems to me, after reading the [Ontology relations](http://geneontology.org/page/ontology-relations) page, that "Part of" should be included. 

 > B is necessarily part of A: wherever B exists, it is as part of A, and the presence of the B implies the presence of A

Is there any reason it is not?

What about the other relationships (regulate, has_part)? I don't think they should be included by default, but maybe an optional argument to get_all_children to include them?

**Comment by tanghaibao** [comment]
Hi Greg,

Good idea. Any interest to submit a patch for this?

Haibao
