### ISSUE TITLE
Error when running find_enrichment.py with --fdr option

### ISSUE THREAD

**Issue by AGrusz** [tanghaibao/goatools#27]
Hi there, 

I am trying to run the "find_enrichment.py" script with the --fdr option. My population of genes is only 2151 and my study sample file(s) is(/are) less than 1000 genes. The Bonferroni numbers seemed very high, which I thought might be due to my sample size. However, when I run "find_enrichment.py" I receive the following errors:

  File "/Users/Grusz/bin/goatools-0.5.2/scripts/find_enrichment.py", line 124, in <module>
    study=study, methods=methods)
  File "/Users/Grusz/bin/goatools-0.5.2/scripts/../goatools/go_enrichment.py", line 95, in __init__
    self.run_study(study)
  File "/Users/Grusz/bin/goatools-0.5.2/scripts/../goatools/go_enrichment.py", line 134, in run_study
    self.term_pop, self.obo_dag)
  File "/Users/Grusz/bin/goatools-0.5.2/scripts/../goatools/multiple_testing.py", line 109, in calc_qval
    new_term_study = go_enrichment.count_terms(new_study, assoc, obo_dag)
NameError: global name 'go_enrichment' is not defined

I've scanned through the "go_enrichment.py" and "mutiple_testing.py" files to see where things are going wrong, but can't seem to find the problem. Any suggestions would be much appreciated.

Thanks, 
Amanda

**Comment by tanghaibao** [comment]
Amanda,

Thanks for reporting this bug. This was due to a cyclic import. Here is the changes that I made:

https://github.com/tanghaibao/goatools/commit/540935f8bfe1c1278c76a1b3032c099c1cd09bae

Please pull these changes and let me know if it works.

Haibao

**Comment by AGrusz** [comment]
Hi Haibao,

I updated with the files you sent and it worked like a charm.

Thank you,
Amanda

On Tue, Mar 10, 2015 at 2:22 PM, Haibao Tang <notifications@github.com>
wrote:

> Amanda,
>
> Thanks for reporting this bug. This was due to a cyclic import. Here is
> the changes that I made:
>
> 540935f
> <https://github.com/tanghaibao/goatools/commit/540935f8bfe1c1278c76a1b3032c099c1cd09bae>
>
> Please pull these changes and let me know if it works.
>
> Haibao
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tanghaibao/goatools/issues/27#issuecomment-78115620>.
>



-- 

Amanda Grusz
Email: amanda.grusz@gmail.com

**Comment by tanghaibao** [comment]
No problem. Let me know if you run into other issues.
