### ISSUE TITLE
Do anyone know the differences between the enriched results and the purifed results after the GOEA analysis of the GOATOOLS?

### ISSUE THREAD

**Issue by Sotdo** [tanghaibao/goatools#285]
After I run the GOEA analysis using the `GOEnrichmentStudyNS` function, the output has a column named **enrichment**. It has two values: e and p, where **e** represents enriched results and **p** represents purified results.  Do anyone know the differences between these two?

**Comment by tanghaibao** [comment]
@Sotdo 

They are opposite trend. 
`e` represent enrichment, which means there are significantly more count in the target term. `p` is the direct opposite, means that there are significantly fewer count in the target term.

**Comment by Sotdo** [comment]
> @Sotdo
> 
> They are opposite trend. `e` represent enrichment, which means there are significantly more count in the target term. `p` is the direct opposite, means that there are significantly fewer count in the target term.

Thansk! That's really helpful!
