### ISSUE TITLE
Left to right plot in go_plot.py?

### ISSUE THREAD

**Issue by SchwarzMarek** [tanghaibao/goatools#288]
Hello,
thank you for the package. 

The plot produced for my data is rather large (as expected, since I have rather large amount of GO terms that I want to show).

I've notices, that the plot could be more compact and readable, if it would be plotted left -> right (or right -> left) with wide labels, instead of top-down.

Is there is setting which could change the graph plot appearance?

Best Marek

**Comment by tanghaibao** [comment]
@SchwarzMarek 

it's not currently configured this way but should be possible. I'll find a time to work on this (busy recently).
thanks for reporting this. alternatively if you find a way to code this up, we'd be happy to take the PR ;-)
