### ISSUE TITLE
"LINK : error LNK2001: unresolved external symbol PyInit_fisher/cfisher"

### ISSUE THREAD

**Issue by Guangyou** [tanghaibao/goatools#37]
Hi All,

I met a problem when I tried to install goatools on Windows 7 system.  I am looking forward to your suggestion!

The python version is 3.4 (32bit). I have installed VS2010. 

The error shows:

Searching for goatools
Best match: goatools 0.5.5
Processing goatools-0.5.5-py3.4.egg
goatools 0.5.5 is already the active version in easy-install.pth
Installing map_to_slim.py script to C:\Python34\Scripts
Installing plot_go_term.py script to C:\Python34\Scripts
Installing write_hierarchy.py script to C:\Python34\Scripts
Installing find_enrichment.py script to C:\Python34\Scripts

Using c:\python34\lib\site-packages\goatools-0.5.5-py3.4.egg
Processing dependencies for goatools
Searching for fisher
Reading https://pypi.python.org/simple/fisher/
Best match: fisher 0.1.4
Downloading https://pypi.python.org/packages/source/f/fisher/fisher-0.1.4.tar.gz#md5=bfc763b7333a1f428e4c447dd8a85968
Processing fisher-0.1.4.tar.gz
Writing C:\Users\Duan\AppData\Local\Temp\easy_install-khjvz9br\fisher-0.1.4\setup.cfg
Running fisher-0.1.4\setup.py -q bdist_egg --dist-dir C:\Users\Duan\AppData\Local\Temp\easy_install-khjvz9br\fisher-0.1.4\egg-dist-tmp-xgn4zhdy
cfisher.c
c:\python34\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
LINK : error LNK2001: unresolved external symbol PyInit_fisher/cfisher
build\temp.win32-3.4\Release\src\cfisher.lib : fatal error LNK1120: 1 unresolved externals

Thanks!

**Comment by tanghaibao** [comment]
This is a known issue in `fishers_exact_test`.

https://github.com/brentp/fishers_exact_test/issues/5

Unfortunately I don't have much experience on compiling modules on Windows.

**Comment by tanghaibao** [comment]
@Guangyou, the related issue in `fishers_exact_test` is now fixed. Please report back if this resolved your issue. Thanks -

https://github.com/brentp/fishers_exact_test/issues/5

**Comment by CFretter** [comment]
Yes, when getting fishers_exact_test from github everything is fine.
easy_install doesn't reflect the change yet though.
