### ISSUE TITLE
Infinite loop when parsing

### ISSUE THREAD

**Issue by CFretter** [tanghaibao/goatools#39]
```python
from goatools.obo_parser import GODag
obo_dag = GODag(obo_file="../GO/go-basicNS.obo")
```
leads to an infinite loop on:
'2.7.9 |Anaconda 2.2.0 (64-bit)| (default, Dec 18 2014, 16:57:52) [MSC v.1500 64 bit (AMD64)]'

the .obo file being:
format-version: 1.2
data-version: releases/2015-06-20
date: 19:06:2015 14:25
saved-by: dph
auto-generated-by: OBO-Edit 2.3.1

I temporarily fixed it in https://github.com/CFretter/goatools/commit/a7aee05ac49f2b1146e83f86fffaf046ada1674d

**Comment by tanghaibao** [comment]
Thanks, I pulled your changes and fixed some indentation issues (it appears that our editor configuration is different).

https://github.com/tanghaibao/goatools/commit/58c97d3a2c9f9fd386b7e9457812612543b422a1

**Comment by tanghaibao** [comment]
@CFretter, this issue is closed but just a quick comment that seek() is no longer used as of goatools-0.5.7 due to fixes by @dvklopfenstein. This fix also considerably improved the performance of the parser.
