### ISSUE TITLE
Method of FDR

### ISSUE THREAD

**Issue by shelkmike** [tanghaibao/goatools#44]
Could you please specify what is a method for False Discovery Rate calculation? Is it Benjamini-Hochberg or Benjamini-Yekutieli?

Thank You

**Comment by tanghaibao** [comment]
@shelkmike, neither. This particular implementation of FDR is based on this study:
http://www.biomedcentral.com/1471-2105/6/168

A few of us (@dvklopfenstein) have talked about implementing the more popular Benjamini-Hochberg at some point but this has not happened yet.

Thanks,
Haibao

**Comment by shelkmike** [comment]
Thank you for your reply, Haibao. Just want to mention, that If you will implement another FDR method, it will be better to use Benjamini-Yekutieli, because Benjamini-Hochberg demands independence of tests which is not the case for GO (for example, increasing a number of proteins with DNA helicase activity (GO:0003678)  you automatically increase a number of proteins working in the nucleus (GO:0005634))

**Comment by tanghaibao** [comment]
@shelkmike thanks for the important note. I'll keep this in mind.
