### ISSUE TITLE
Comparison studies and fisher.pvalue_population

### ISSUE THREAD

**Issue by yunesj** [tanghaibao/goatools#46]
`fisher.pvalue_population` is defined like this:

```
# k, n = study_true, study_tot,
# C, G = population_true, population_tot
def pvalue_population(int k, int n, int C, int G):
    #print "k=%i, n=%i, C=%i, G=%i" % (k, n, C, G)
    return pvalue(k, n - k, C - k, G - C - n + k)
```

This suggests that population_true and population_tot must include the respective counts from study_true and study_tot, since those counts will be subtracted.

However, in `find_enrichment.read_geneset()`, you explicitly make sure the population does not include the common terms when "comparing":

```
    if compare:
        ...
        pop -= common
```

Should the study set actually be added to the comparison set instead? Alternatively, should another function besides `fisher.pvalue_population` be used?

**Comment by tanghaibao** [comment]
@yunesj, I think you are right. I could not remember the initial motive for the ``--compare`` option now - but this does not make sense as you pointed out. Would you commit a change? Thanks -
