### ISSUE TITLE
fisher import error

### ISSUE THREAD

**Issue by idoerg** [tanghaibao/goatools#49]
Python 3.4

```

>>> import fisher
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/fisher-0.1.4-py3.4-linux-x86_64.egg/fisher/__init__.py", line 1, in <module>
    from cfisher import *
ImportError: No module named 'cfisher'

```

Fix:
Looks like a Python3 compatibility issue

```
 __init__.py

from __future__ import absolute_import
from .cfisher import *
```

**Comment by dvklopfenstein** [comment]
Thank you for your time and interest in GOATOOLS. We have added using the fisher functions from the scipy package. Now, if the fisher function from one source fails to run on your machine, we try the scipy fisher function. We are closing this issue as hopefully, it has been resolved. Please feel free to open a new issue if this does not resolve your issue or if you have a new question. Thank you for contacting GOATOOLS.
