### ISSUE TITLE
import error (python2.7)

### ISSUE THREAD

**Issue by gserrano92** [tanghaibao/goatools#55]
Traceback (most recent call last):
  File "scripts/find_enrichment.py", line 25, in <module>
    from goatools.go_enrichment import GOEnrichmentStudy
  File "scripts/../goatools/__init__.py", line 5, in <module>
    from goatools.go_enrichment import *
  File "scripts/../goatools/go_enrichment.py", line 18, in <module>
    import fisher
ImportError: No module named fisher

**Comment by dvklopfenstein** [comment]
Thank you for your question. Can you check that the "fisher" package installed on your machine?:

pip install fisher

$ python
Python 2.7.10 (default, Jun  1 2015, 18:05:38)
[GCC 4.9.2] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fisher
>>> help(fisher)

**Comment by gserrano92** [comment]
Processing fishers_exact_test
Writing /Users/Genesis/fishers_exact_test/setup.cfg
Running setup.py -q bdist_egg --dist-dir /Users/Genesis/fishers_exact_test/egg-dist-tmp-w4e7Pm
zip_safe flag not set; analyzing archive contents...
fisher 0.1.5 is already the active version in easy-install.pth

Installed /Library/Python/2.7/site-packages/fisher-0.1.5-py2.7-macosx-10.11-intel.egg
Processing dependencies for fisher==0.1.5
Finished processing dependencies for fisher==0.1.5
Genesiss-MacBook-Pro:~ Genesis$ import fisher
-bash: import: command not found

**Comment by fidelram** [comment]
I think you already have installed fisher.

Can you try again to run goatools?

The `import fisher` that you tried will not work because you need to run
those commands within the python shell. In case you want to try, simply
type 'python' to enter the python shell. Then you can run 'import fisher'
etc.



On Sun, Mar 20, 2016 at 12:01 AM, gserrano92 <notifications@github.com>
wrote:

> Processing fishers_exact_test
> Writing /Users/Genesis/fishers_exact_test/setup.cfg
> Running setup.py -q bdist_egg --dist-dir
> /Users/Genesis/fishers_exact_test/egg-dist-tmp-w4e7Pm
> zip_safe flag not set; analyzing archive contents...
> fisher 0.1.5 is already the active version in easy-install.pth
>
> Installed
> /Library/Python/2.7/site-packages/fisher-0.1.5-py2.7-macosx-10.11-intel.egg
> Processing dependencies for fisher==0.1.5
> Finished processing dependencies for fisher==0.1.5
> Genesiss-MacBook-Pro:~ Genesis$ import fisher
> -bash: import: command not found
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tanghaibao/goatools/issues/55#issuecomment-198804521>
>



-- 

Fidel Ramirez

**Comment by gserrano92** [comment]
SOLVED

**Comment by tanghaibao** [comment]
@gserrano92 thanks for reporting back. Closing this issue now.
