### ISSUE TITLE
go_enrichment  ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by gserrano92** [tanghaibao/goatools#56]
> python /Users/Genesis/Downloads/goatools-0.6.4/goatools/go_enrichment.py /Users/Genesis/Desktop/data/study.txt /Users/Genesis/Desktop/data/population.txt /Users/Genesis/Desktop/data/association.txt
> Traceback (most recent call last):
>   File "/Users/Genesis/Downloads/goatools-0.6.4/goatools/go_enrichment.py", line 22, in <module>
>     from multiple_testing import Methods, Bonferroni, Sidak, HolmBonferroni, FDR, calc_qval
>   File "/Users/Genesis/Downloads/goatools-0.6.4/goatools/multiple_testing.py", line 12, in <module>
>     from .ratio import count_terms
> ValueError: Attempted relative import in non-package

**Comment by dvklopfenstein** [comment]
Thank you for your interest in GOATOOLS and taking the time to report this issue.
We were not able to duplicate this error. Please re-open if this is still an issue.
