### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by bebatut** [tanghaibao/goatools#58]
Hello,

I recently developed a `conda` package for `goatools`.
More [info](https://bioconda.github.io/recipes/goatools/README.html?highlight=goatools).

If you want, you can add the following badge:
[![bioconda-badge](https://img.shields.io/badge/install%20with-bioconda-brightgreen.svg?style=flat-square)](http://bioconda.github.io)

Bérénice

**Comment by tanghaibao** [comment]
@bebatut thanks for adding the package! I'll add the badge when I get a chance - Haibao

**Comment by themantalope** [comment]
I have a question regarding installation of `goatools` using conda with a python version 3.5+. Is the package compatible with python 3.5, or is it simply that installation through conda only allows python2.7? I get this error when trying to install `goatools` using conda in a python 3.5 environment:

```bash
$ conda install goatools
Fetching package metadata ...............
Solving package specifications: ....


UnsatisfiableError: The following specifications were found to be in conflict:
  - goatools
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by dvklopfenstein** [comment]
@olgabot Would you mind taking a look at this conda issue?
