### ISSUE TITLE
Error printing GOTerm

### ISSUE THREAD

**Issue by deto** [tanghaibao/goatools#61]
If I try to read an obo file with OBOReader, printing GO terms is generating an error.

```
import goatools
reader = goatools.obo_parser.OBOReader('go-basic.obo')
go_terms = list(reader)
go_terms[0]
TypeError                                 Traceback (most recent call last)
C:\Anaconda\lib\site-packages\IPython\core\formatters.pyc in __call__(self, obj)
    697                 type_pprinters=self.type_printers,
    698                 deferred_pprinters=self.deferred_printers)
--> 699             printer.pretty(obj)
    700             printer.flush()
    701             return stream.getvalue()

C:\Anaconda\lib\site-packages\IPython\lib\pretty.pyc in pretty(self, obj)
    381                             if callable(meth):
    382                                 return meth(obj, self, cycle)
--> 383             return _default_pprint(obj, self, cycle)
    384         finally:
    385             self.end_group()

C:\Anaconda\lib\site-packages\IPython\lib\pretty.pyc in _default_pprint(obj, p, cycle)
    501     if _safe_getattr(klass, '__repr__', None) not in _baseclass_reprs:
    502         # A user-provided repr. Find newlines and replace them with p.break_()
--> 503         _repr_pprint(obj, p, cycle)
    504         return
    505     p.begin_group(1, '<')

C:\Anaconda\lib\site-packages\IPython\lib\pretty.pyc in _repr_pprint(obj, p, cycle)
    692     """A pprint that just redirects to the normal repr function."""
    693     # Find newlines and replace them with p.break_()
--> 694     output = repr(obj)
    695     for idx,output_line in enumerate(output.splitlines()):
    696         if idx:

C:\Anaconda\lib\site-packages\goatools\obo_parser.pyc in __repr__(self)
    207                 ret.append("{K}:{V}".format(K=key, V=val))
    208             else:
--> 209                 ret.append("{K}: {V} items".format(K=key, V=len(val)))
    210                 if len(val) < 10:
    211                     for elem in val:

TypeError: object of type 'NoneType' has no len()
```

**Comment by dvklopfenstein** [comment]
Deto, 

Thank you for using GOATOOLs and thank you for bringing this to our attention. 

The issue seems to be the GOTerm class's __str__ function. It was expecting an integer, even if the level and depth GOTerm attributes were not yet assigned. The GODag class initializes these values.

I have modified the GOTerm __str__ function so that it will print the level and depth, even if they are in their uninitialized value of "None".

There is now a new test created using the text in your email. Please let us know if this works for you.

Thank you again for using GOATOOLs and for our contribution.

DV

**Comment by deto** [comment]
Ah, I didn't notice it in the str method - rather it was happening to me in the repr method (which iPython uses in its default display through prettyprint).  See my attempt at fixing in the pull-request for reference (no need to pull it in, though, if you had a different way of fixing in mind).

**Comment by dvklopfenstein** [comment]
Your pull request is still a good idea. But yes, it looks like in calling __str__ when attempting to convert a GO Term to a sting value for printing, it was failing if level and depth were not initialized from None. Please let us know if you see any further issues.

I also see the fisher message in my own runs. I've contacted people who can hopefully help. I normally run on cygwin and it is not an issue there. When using Windows while developing iPython notebooks it pops up.
