### ISSUE TITLE
error using Python 3.5

### ISSUE THREAD

**Issue by adelomana** [tanghaibao/goatools#66]
Hi, 

I'm just trying to use your tool (thanks for developing!) but it seems there's an error in my environment. Is it a Python 3 compatibility?

Thanks so much!

python ~/anaconda/bin/find_enrichment.py --pval=0.01 --indent /Users/alomana/scratch/temporalFile.txt /Users/alomana/gDrive2/projects/TREES-C/PfuEGRIN/data/go/populationFile.txt /Users/alomana/gDrive2/projects/TREES-C/PfuEGRIN/data/go/associationFile.txt
Study: 4 vs. Population 1462
load obo file go-basic.obo
go-basic.obo: format-version(1.2) data-version(releases/2016-09-10)
47199 nodes imported
Traceback (most recent call last):
  File "/Users/alomana/anaconda/bin/find_enrichment.py", line 4, in <module>
    **import**('pkg_resources').run_script('goatools==0.6.5', 'find_enrichment.py')
  File "/Users/alomana/anaconda/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/**init**.py", line 719, in run_script
  File "/Users/alomana/anaconda/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/**init**.py", line 1511, in run_script
  File "/Users/alomana/anaconda/lib/python3.5/site-packages/goatools-0.6.5-py3.5.egg/EGG-INFO/scripts/find_enrichment.py", line 137, in <module>
  File "/Users/alomana/anaconda/lib/python3.5/site-packages/goatools-0.6.5-py3.5.egg/goatools/go_enrichment.py", line 207, in **init**
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'

Python 3.5.2 |Anaconda 4.1.1 (x86_64)| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

**Comment by dvklopfenstein** [comment]
I am away right now, but will take a look at it during a break. Thank you very much for using GOATOOLS. Thank you for bringing this to our attention.

**Comment by dvklopfenstein** [comment]
Hi, I just looked at the code. This has been corrected in the current code. But the version in PyPi does not have the latest code. 

I'll ask our project owner to release a new version. 

In the meantime, you can do any of these:
1. Download the latest GOATOOLS code from GitHub.
2. Edit your local files. For example, in /Users/alomana/anaconda/lib/python3.5/site-packages/goatools-0.6.5-py3.5.egg/goatools/go_enrichment.py, you would change this

WAS:
            print >> sys.stderr, "Propagating term counts to parents .."
            obo_dag.update_association(assoc)

CHANGE TO:
            sys.stdout.write("Propagating term counts to parents ..\n")
            obo_dag.update_association(assoc)

**Comment by tanghaibao** [comment]
@dvklopfenstein please let me know if it is time to build a new version for this.

**Comment by dvklopfenstein** [comment]
Yes. It is time to build a new version. Thank you.
