### ISSUE TITLE
The bug about more than one relationship in obo file

### ISSUE THREAD

**Issue by NightKight** [tanghaibao/goatools#73]
here is the code in obo_parser.py

        if hasattr(rec, name):
            if name not in self.attrs_scalar:
                if name not in self.attrs_nested:
                    getattr(rec, name).add(value)
                else:
                    self._add_nested(rec, name, value)
            else:
                raise Exception("ATTR({NAME}) ALREADY SET({VAL})".format(
                    NAME=name, VAL=getattr(rec, name)))
        else: # Initialize new GOTerm attr
            if name in self.attrs_scalar:
                setattr(rec, name, value)
            elif name not in self.attrs_nested:
                setattr(rec, name, set([value]))
            else:
                name = '_{:s}'.format(name)
                setattr(rec, name, defaultdict(list))
                self._add_nested(rec, name, value)

here, this code, if hasattr(rec, name), is never true, because name is relationship but the attr is _relationship by name = '_{:s}'.format(name), so only the last one relationship of each go_term saved.
And I change the code like this:

        _name = '_{:s}'.format(name) if name in self.attrs_nested else name
        if hasattr(rec, _name):
            if name not in self.attrs_scalar:
                if name not in self.attrs_nested:
                    getattr(rec, name).add(value)
                else:
                    self._add_nested(rec, _name, value)
            else:
                raise Exception("ATTR({NAME}) ALREADY SET({VAL})".format(
                    NAME=name, VAL=getattr(rec, name)))
        else: # Initialize new GOTerm attr
            if name in self.attrs_scalar:
                setattr(rec, name, value)
            elif name not in self.attrs_nested:
                setattr(rec, name, set([value]))
            else:
                # name = '_{:s}'.format(name)
                setattr(rec, _name, defaultdict(list))
                self._add_nested(rec, _name, value)

Thanks a lot.

**Comment by dvklopfenstein** [comment]
Thank you for using GOATOOLS and thank you for taking the time to provide this feedback. I will take a look at it in the next few days.

**Comment by dvklopfenstein** [comment]
Thank you for taking the time to report this issue. The referenced commit hashes should fix this issue and so this issue will be closed. Please open a new issue if needed. Thank you again for your interest in GOATOOLS and for taking the time to submit this issue.
