### ISSUE TITLE
Is there an option to custom the output columns of wr_xlsx

### ISSUE THREAD

**Issue by illxi** [tanghaibao/goatools#74]
is it possible to custom the columns of the excel tables generated by goeaobj.wr_xlsx? 

for example I want to export columns:
"ratio_in_study", "ratio_in_pop"

**Comment by dvklopfenstein** [comment]
Thank you for interest in GOATOOLS and thank you for your question.

Yes, you can customize the output columns in wr_xlsx. The 'prt_flds'
keyword argument allows you to both control the order of the columns and
print either all or a subset of namedtuple fields.

The 'hdrs' keyword argument allows you to change the top header line from
the names of the namedtuple fields to header text of your choosing.

Does this help? If not, if you could provide us a code example, we could
provide specific examples.

Thank you again for your time and your feedback.

DV

**Comment by illxi** [comment]
Thank you for your reply. I try the following code, but the excel file has ratio_in_study and ratio_in_pop field blank.
goeaobj.wr_xlsx(job_name+"_raw.xlsx", goea_results_all, prt_flds=['GO', 'NS', 'enrichment', 'name', 'ratio_in_study', 'ratio_in_pop', 'p_uncorrected', 'depth', 'study_count'])

but if I print it on python, it will display correctly.
print goea_results_all[0].ratio_in_study
(5, 117)

any idea?

**Comment by dvklopfenstein** [comment]
Can you include your entire script which calculates goea_results? It would
be helpful to have your data files too. Then we could re-create your
situation.

**Comment by dvklopfenstein** [comment]
illxi,

Try this:

Instead of "ratio_in_study", use these two: "study_count", "study_n":

    goea_results = goeaobj.run_study(study_ids)
    prt_flds = ["GO", "NS", "enrichment", "name"]
    # Print these fields instead of: ratio_in_study ratio_in_pop
    prt_flds.extend(["study_count", "study_n", "pop_count", "pop_n"])
    prt_flds.extend(["p_uncorrected", "depth", "p_bonferroni",
"study_items"])
    goeaobj.wr_xlsx(fout_xlsx, goea_results, prt_flds=prt_flds)

**Comment by dvklopfenstein** [comment]
Also, what version of goatools are you using? Did you get it using one of
the install programs (pip, easy_install) or did you fork or clone?

Here is how to get the version:

$ python
Python 2.7.12 (default, Oct 10 2016, 12:56:26)
[GCC 5.4.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import goatools
>>> goatools.__version__
'0.6.10'
>>> quit()

**Comment by illxi** [comment]
Thank you very much! I changed "ratio_in_study" and "ratio_in_pop" to "study_count", "study_n", "pop_count" and "pop_n". It worked! 

btw, my python is 2.7.12, and goatools version 0.6.10.

**Comment by dvklopfenstein** [comment]
I am so glad that you are up and running.

If you got GOATOOLS from one of the install packages, we probably need to
create a new version as the code in the repo is a little bit ahead of the
version available with the install tools. We will take care of that. After
the update, you should be able to use ether set of fields.

Thank you very much for your interest in GOATOOLS and thank you for your
feedback.

DV
