### ISSUE TITLE
Does goatools work with every obo ontology and gaf annotations?

### ISSUE THREAD

**Issue by dandaman** [tanghaibao/goatools#77]
Hi,

I am looking for a tool that can be used to look for enrichment based on GAF and obo  of any ontology. E.g. plant ontology PO, TO, EO...

Is this possible with goatools?

Best,
Daniel

**Comment by dvklopfenstein** [comment]
GOATOOLS has over 100 web citations, with many for gene ontology analyses on plants, so it will likely work. If you try it and it works out please let us know which plant species you worked with. If you have any issues, please send us a sample of your input files and we would be happy to help you make it work.

**Comment by dvklopfenstein** [comment]
We are going to close this issue for now as we have not heard back, hopefully your question is resolved. If not, please feel free to open an new issue. Thank you for your time and interest in GOATOOLS.

**Comment by dvklopfenstein** [comment]
Closing...
