### ISSUE TITLE
conda does not install properly when using python 3.4

### ISSUE THREAD

**Issue by JudoWill** [tanghaibao/goatools#87]
Something seems weird with the bioconda installation. Trying to install goatools through bioconda into a new python 3 environment leads to a UnsatisfiableError. However it installs just fine into the same environment using pip.

**Comment by dvklopfenstein** [comment]
Dr. Dampier,

Thank you for your interest in GOATOOLS and taking the time to contact to let us know of this error message.

Can you please add to the issue report:
1) What commands were run which resulted in this error?
2) Please copy the full screen output of the full log starting from running the command to the final error.

**Comment by tanghaibao** [comment]
The `fisher` dependency has been removed from conda package so this specific issue should have been fixed. However, there may be other issues in conda, tracked more recently in #197.
