### ISSUE TITLE
TermsCount(Go,Association) not working for human genes - goa_human.gaf

### ISSUE THREAD

**Issue by MuhammadZeeshan34** [tanghaibao/goatools#88]
It works perfectly when I use _Arabidopsis thaliana_ but when I try to use any _Homo sapiens_ I get error while computing TermsCount. 

Here is errTraceback:

`Traceback (most recent call last):
  File "/Users/zeeshannawaz/wp-tomoe-angiogenesis/src/angen/embed/preglove/go/gene_ontology_wrapper.py", line 88, in <module>
    termcounts = TermCounts(go, associations)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/goatools/semantic.py", line 31, in __init__
    self._count_terms(godag, annots)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/goatools/semantic.py", line 42, in _count_terms
    allterms |= godag[go_id].get_all_parents()
KeyError: 'GO:0102756'`

**Comment by dvklopfenstein** [comment]
Thank you for your interest in GOATOOLS and taking the time to contact us regarding the error that you are seeing. I am investigating it now.

**Comment by dvklopfenstein** [comment]
I have updated the code to be more robust in case of association/GODag mismatches. Please do a pull and re-run the script that accesses TermCounts. Please let us know if this code change works for you.

After testing that the code changes work, you may want to re-download both your associations and the GODag. They may be out of sync. I just ran TermCounts on numerous associations that were just downloaded and a GODag containing data for a go-basic.obo file which was also just downloaded.

Please let us know how the code updates work for you. Thank you again for your interest in GOATOOLS and taking the time to log this issue.

**Comment by dvklopfenstein** [comment]
We believe that the code changes address your issue. If they do not, please open an new issue and we will pursue it.

Thank you for taking the time to report this issue. Thank you for your interest in GOATOOLS.
