### ISSUE TITLE
0.7.10 setuptools issue

### ISSUE THREAD

**Issue by yunesj** [tanghaibao/goatools#90]
```
$ pip install goatools
Collecting goatools
  Using cached goatools-0.7.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jw/23sjzsn97lz8qj3kp4bg4pw00000gn/T/pip-build-OpOQPw/goatools/setup.py", line 8, in <module>
        from setup_helper import SetupHelper
    ImportError: No module named setup_helper
```

**Comment by dvklopfenstein** [comment]
Thank you very much for taking your time to make GOATOOLS installations more robust. If you happen to look into this before we get a chance and create a pull request which fixes the issue, it will be very much appreciated. Otherwise, we will take a look as soon as we can.

**Comment by tanghaibao** [comment]
@yunesj 
Thanks for raising this issue - I forgot to include a script in MANIFEST.in and I think I have fixed the issue in 0.7.11.

**Comment by yunesj** [comment]
Thanks!!

**Comment by dvklopfenstein** [comment]
Hi Jeff, I am going to close this issue as I believe that it has been addressed. Thank you for taking the time to report this. If it is not properly addressed, please open a new issue. Thank you for being a contributor to GOATOOLS.
