### ISSUE TITLE
Get infos about not enriched GO terms

### ISSUE THREAD

**Issue by CIWa** [tanghaibao/goatools#91]
Dear all,

Is there a way to get the infos about all the GO terms associated with the study items of the enrichment analysis, and not only the significantly enriched/purified GO terms?

Thank you very much,
and best wishes,
Isabel

**Comment by dvklopfenstein** [comment]
Thank you very much for your interest in GOATOOLS and for taking the time to contact us.

Yes, there are a number of ways to get information about all GO terms associated with the study items of an enrichment analysis, not just the significant GO terms.

Are you getting the GO IDs using the scripts/find_enrichment.py script from the command-line or are you running GOEAs from your own script? Can you provide an example of the command-line that you run?

In the meantime, if you are using your own script, this test (shows how you can write both significant GO IDs only (nbt3102_sig_symbols.xlsx) and ALL GO IDs (nbt3102_all_symbols.xlsx).

Please do a 'git pull' as I just added the lines to write ALL GO IDs to that script.

Thank you again for taking your time to contact us. Thank you for your usage of GOATOOLS.

**Comment by CIWa** [comment]
Thank you for your fast answer! I am using the find_enrichment.py script from the command line. My call is:
python find_enrichment.py  --pval=0.05 --indent StudySeqs.txt AllSeqs.txt GOMapping.txt --outfile Results.txt
I am thinking about setting the p-value to 1. That should do the job, I guess?
Thanks again,
and best wishes,
Isabel

**Comment by dvklopfenstein** [comment]
CIWa,

Yes, if you set --pval=1.00, then your report will contain all items which have a P-value. --pval has no affect on the calculations:

--pval sets the masking for pruning GO ID that you may not want in Results.txt
--alpha sets the allowable percentage of false positives when doing multiple-test correction.

Please do a pull as I have updated the informational messages to the screen to bettter show the difference between find_enrichment.py's use of the --pval and --alpha arguments.

Thank you again for using GOATOOLS and for your question.

DV
