### ISSUE TITLE
Do you have plans to allow parsing of part_of and other relationships as parent-children connections?

### ISSUE THREAD

**Issue by Melnorme1984** [tanghaibao/goatools#92]
The current "nested structure" implementation for relationships doesn't allow one to use `update_association` to propagate on them.

**Comment by Melnorme1984** [comment]
I deal with this right now by replacing GOTerm's `get_all_parents` with a customized version:

```
def get_all_parents(self):
    """Return all parent GO IDs."""
    all_parents = set()
    for parent in itertools.chain(self.parents, getattr(self, "relationship", collections.defaultdict(set))["part_of"]):
        all_parents.add(parent.id)
        all_parents |= parent.get_all_parents()
    return all_parents
```

**Comment by dvklopfenstein** [comment]
Hello Melnorme1984, 

Thank you for your interest in GOATOOLS and thank you for contacting us. 

We do plan to update this function to use new code (currently in an alpha repo, but will be released upon the publication of our GOATOOLS manuscript). Your request had not been in our immediate plans, but with user interest it makes sense to do it.

Could you provide a short test(s) demonstrating how you would use this in one of your scripts? With the test, we could be sure that we are both thinking the same way and have not missed anything.

Thank you again for your interest and GOATOOLS and for providing us with this information and your current customize version.

**Comment by dvklopfenstein** [comment]
FYI, I am working on supporting the 'part_of' relationship now as I need it currently in my own research. I'll post back with links to tests where part_of is used. Thank you for taking the time to contact us and express your interest in the part_of relationship .

**Comment by dvklopfenstein** [comment]
Thank you very much for your interest in GOATOOLS and taking the time to express interest in this important functionality.

BRAND NEW are the functions:
  * get_all_upper()
  * get_all_lower()

which traverse both the get_all_parents/get_all_children as well as the relationships and reverse relationships: (tests/test_i92_relationship_parentchild.py)

It is planned to use these new functions in "propagate_counts". 
We will update the code for the version of "propagate_counts" that you need once our manuscript (and related code) is out.

Please open a new request for propagate_counts using relationships. In the meantime, please use the new functions, get_all_upper() and get_all_lower() in place of your modified get_all_parents() and get_all_children().

I am closing this issue. Please re-open if there are any issues with the NEW get_all_upper() and get_all_lower().

**Comment by dgpinheiro** [comment]
Sorry, but I used these functions without success. I also interested in an implementation considering relationships, such as part_of, to propagate counts on them.

**Comment by dvklopfenstein** [comment]
Thank you for your interest in GOATOOLS and taking the time to write to us.

I will take a look at propagate_counts allowing the use of othre relationships shortly. Issue #117 is now being used to track this request.

Thank you again for expressing user priorities.
