### ISSUE TITLE
Add "force_dnld" parameter and other improvements to download functions in base.py/associations.py

### ISSUE THREAD

**Issue by Melnorme1984** [tanghaibao/goatools#94]
The `dnld_ncbi_gene_file` function in associations.py has a `force_dnld` parameter that forces the function download the NCBI Gene2GO file even if it's already there.

I think this should also be available in the `download_go_basic_obo` download function in base.py, for applications that want to maintain up-to-date data files at all times. And also all other download functions in the library.

Another thing that could be nice is a separate parameter for selecting a directory to download files to.

And of course, all of these parameters should also be available in the "getter" functions like `get_godag` and `get_assoc_ncbi_taxids` that both download and read the files.

By the way, why are Gene2GO and GAF download functions duplicated in both base.py and associations.py?

**Comment by dvklopfenstein** [comment]
Melnorme1984,

Adding force_dnld to the get_ scripts is a great idea. If you would like to implement this functionality, we welcome your efforts. 

Prior to submitting your pull request:
  * Add a test(s) which test the new force_dnld functionality for each updated function
  * pylint your tests and new code
  * Do 'make test' from the goatools repo root directory to run all tests.

Please ensure any changes that you make will not affect people already using those functions.

Thank you for your interest in GOATOOLS and your useful suggestions.

**Comment by dvklopfenstein** [comment]
I attached the "help wanted" label to this code request. Melnorme1984's idea is a good one. I do not have time to make this change right now. If anyone is interested, your contributions will be much appreciated.
